### ISSUE TITLE
Allowing ORM objects in filter() function

### ISSUE THREAD

**Issue by ConneXNL** [tommikaikkonen/redux-orm#10]
[First of all I have to say that your library is incredible. I am currently playing with it and it might fix the doubts I had on React + Redux in comparison with the OO Backbone/Ampersand.js apps.]

So far everything just works.

I would however like to request a feature on the filter() object so that the folllowing can work out of the box:

schema.get('ModelA').filter({
         modelB: schema.get('ModelB').withId(2), 
         modelC: schema.get('ModelC').withId(1)
});

Currently you have to call the id property:
schema.get('ModelA').filter({
         modelB: schema.get('ModelB').withId(2).id, 
         modelC: schema.get('ModelC').withId(1).id
});

It would be a nice feature if the filter() function types check for ORM Models and converts the values to Ids automatically.

**Comment by tommikaikkonen** [comment]
Hi! You should be able to do this now in `0.6.0`, see https://github.com/tommikaikkonen/redux-orm/commit/8680f35df3e97bae210eab612b992b050b08ee3b

**Comment by thedeeno** [comment]
Can we close this? @ConneXNL you can always reopen when you get around to re-testing.
