### ISSUE TITLE
Model#markAccessed bug with solution

### ISSUE THREAD

**Issue by Aryk** [tommikaikkonen/redux-orm#100]
https://github.com/tommikaikkonen/redux-orm/blob/master/src/Model.js#L129

I believe there is a bug here in the code. `this.session.markAccessed(this);` expects a string, but we are passing through a class, when really it should be:

```js
this.session.markAccessed(this.modelName);
```

**Comment by Aryk** [comment]
@tommikaikkonen - any thoughts on this? I reckon it's a bug, but maybe I'm missing something...

**Comment by haveyaseen** [comment]
Fixed with v0.10.0.
