### ISSUE TITLE
Updating an object that has an empty relationship

### ISSUE THREAD

**Issue by chanan** [tommikaikkonen/redux-orm#101]
I have an object Item that has m2m field Sections

When a particular Item has no sections, and I call update on the item I get an error:
```
Uncaught TypeError: Cannot read property 'map' of undefined
    at SessionBoundModel.update (http://localhost:3000/static/js/bundle.js:58601:67)
    at Function.reducer (http://localhost:3000/static/js/bundle.js:62372:56)
    at http://localhost:3000/static/js/bundle.js:61660:25
    at Array.forEach (native)
    at defaultUpdater (http://localhost:3000/static/js/bundle.js:61657:33)
    at http://localhost:3000/static/js/bundle.js:61669:10
    at combination (http://localhost:3000/static/js/bundle.js:38529:30)
    at computeNextEntry (<anonymous>:2:26448)
    at recomputeStates (<anonymous>:2:26748)
    at <anonymous>:2:30301
```

Note: To get around the error I can do the following before the update:
```
if(updateObj.sections === undefined || updateObj.sections.length === 0) delete updateObj.sections
```

**Comment by chanan** [comment]
Update: This seems to happen even if the association is not empty.
If I do something along the lines of:
```
const updateObj = Item.withId(1).ref
updateObj.name = "New Name"
Item.withId(1).update(updateObj)
```
I get the error above. If I print out the updateObj to console, it shows a field called sections being undefined.

**Comment by haveyaseen** [comment]
@chanan This problem will probably still be there in v0.10.2. Judging from your workaround I'd assume the error occurs in `Model#_refreshMany2Many`, specifically this line:
```javascript
const normalizedNewIds = values.map(normalizeEntity);
```
`values` in this case would be the `updateObj.sections` which can be `undefined` at times. The code basically doesn't expect you to pass `undefined` as the value for a  `many()` field. In fact I approve of this behavior as anything else would make the ORM guess what you are trying to achieve.

Instead we should detect this case (`relations[name]` being undefined) in `Model._refreshMany2Many` and throw an Error that explains the problem. Doing this in `Model#update` would be a bad idea as it can just as well happen in `Model#create`.
