### ISSUE TITLE
Thoughts on redux-orm foreign keys and associations

### ISSUE THREAD

**Issue by Aryk** [tommikaikkonen/redux-orm#102]
From what I understand, redux orm overloads the fk association names with both the record and the foreign key (via ref). This seems odd to me since no matter how you define your association ("user", or "userId"), something will be strange.

If I'm getting fields from an API, and I have foreign keys from the api like "userId", I essentially have to do something like `modelAttrs.user = api.result.userId` to get it working, as opposed to simply passing `api.result` through as the attributes so they map one-to-one.

If I name the fk as "userId", then this will work, but then my code will look strange wherever I do `model.userId.firstName` 

@tommikaikkonen - just curious, what was the reason for this design choice? Why not separate out the two, the association and the foreign key column as associationId?

**Comment by markerikson** [comment]
I have to say that kinda bothers me to just a bit :)    Would be nice if there was a way to specify the key field and the generated lookup field separately.

**Comment by ernsheong** [comment]
Just encountered this oddness. Perhaps `redux-orm` should simply stick to literal `userId` as the actual id itself, and in addition to that define an additional `.user` on the model to access the relation.
