### ISSUE TITLE
Question: Is there any way to integrate with redux-act?

### ISSUE THREAD

**Issue by RealDeanZhao** [tommikaikkonen/redux-orm#103]
Is there a way to integrate with [redux-act](https://github.com/pauldijou/redux-act), the action creator lib for redux.

**Comment by markerikson** [comment]
Integrate in what way?  Can you clarify what you want to do?

For what it's worth, you can certainly write reducer functions that use Redux-ORM to do the work internally.  I've got some examples of doing that in my blog posts [Practical Redux, Part 1: Redux-ORM Basics](http://blog.isquaredsoftware.com/2016/10/practical-redux-part-1-redux-orm-basics/) and [
Practical Redux, Part 2: Redux-ORM Concepts and Techniques](http://blog.isquaredsoftware.com/2016/10/practical-redux-part-2-redux-orm-concepts-and-techniques/).

**Comment by RealDeanZhao** [comment]
@markerikson thanks for you quick response.
I would like to use redux-act to create the actions so that I don't need to write a lot of switch statement inside a reducer.
```
 static reducer(action, Model, session) {
        switch (action.type) {
                ....
        }
}
```
to this for less boilerplate:
```
[action] : (state) => state + 1;
```

**Comment by RealDeanZhao** [comment]
@markerikson Thank you all the same. I have implemented it.

The new reducer creator:
```
import { createAction, createReducer } from 'redux-act';

import orm from '../orm';

export default function createOrmReducer() {
    const session = orm.session(orm.getEmptyState());
    let actionHandler = {};
    session.sessionBoundModels.forEach(modelClass => {
        if (typeof modelClass.actionHandler === 'function') {
            Object.assign(actionHandler, modelClass.actionHandler());
        }
    });
    return createReducer(actionHandler, session.state);
}

```
In the model class:
```
static actionHandler() {
        return {
            [someAction]: (state, payload) => {
                const session = orm.session(state || state.getEmptyState());
                const { Model } = session;
                Model.delete();
                return session.state;
            }
        }
}
```
