### ISSUE TITLE
Why couple to redux?

### ISSUE THREAD

**Issue by thedeeno** [tommikaikkonen/redux-orm#105]
Loving the look of this framework. I might adopt for my team and get involved. Curious though, why couple this to redux?

Do you find this library useful only when used with redux?

P.S. I think you should give others the ability to create labels and apply them. I could help clean up the issues backlog with them. For example, this is a question, not an issue.

**Comment by Elijen** [comment]
I think last few versions was decoupling from Redux. I also think it would be great to have an ORM completely independent from Redux and perhaps a separate driver that would add the Redux support.

**Comment by markerikson** [comment]
Despite the name, if you look at `package.json`, you'll see that `redux-orm` doesn't actually depend on `redux` in any way.  It was definitely developed with the intent of using it in Redux apps, but you _should_ be able to use it in any JS app, as it really just operates on plain JS objects.

**Comment by thedeeno** [comment]
Excellent! I see now that 0.9 made major steps towards full decoupling. I'm pumped.
