### ISSUE TITLE
Selector is not running while orm state has changed

### ISSUE THREAD

**Issue by nealoke** [tommikaikkonen/redux-orm#117]
Currently using the following selector to get the data of a `patient` from the orm database:
```
export const patientSelector = createSelector(orm, ormSelector, hashSelector, (session, hash) => {
	const patient = session.Patient.withId(hash);
	const consultations = patient.consultations.count();
	const therapies = patient.therapies.count();

	return session.Patient.hasId(hash) ? {
		...patient.ref,
		totalConsultations: consultations,
		totalTherapies: therapies
	} : null;
});

```

But after I update a deeper property (`patient.resources.medicalFiles`) it does not recognize the change and the selector does not update to the new state, so the component does not re-render. Looking at the redux devtools you can see the state has changed.

![image](https://cloud.githubusercontent.com/assets/17417414/25063627/2a8dcefc-21ea-11e7-9438-4df418a6c1b7.png)

Reducer
```
case ActionTypes.ADD_PATIENT_MEDICAL_FILE:
	const resources = Patient.withId(payload.patient).ref.resources;
	const medicalFiles = resources.medicalFiles || [];
	medicalFiles.push({name: payload.name, url: payload.url})

	Patient.withId(payload.patient).update({
		resources: {
			...resources,
			medicalFiles: medicalFiles
		}
	});
break;
```

Any ideas about this?

**Comment by nealoke** [comment]
You guys any idea on how to resolve this? @chanan @markerikson

**Comment by chanan** [comment]
I think I ran into the same issue. What I ended up doing (and this worked for me with my model, but may or may not work for you) - is I added lastUpdateAt property on the top level object (patient) in your case and every time I touched anything in the object, I change the timestamp on the object. I think that is what solved my problem. Not guarantees  though :)

**Comment by nealoke** [comment]
@chanan yhea, I currently fixed it with a `seed` property on the model which is literally just `Math.random()` every time I do the update.

Do you think this is a possible improvement for the library?

**Comment by markerikson** [comment]
@nealoke: Hmm.  I see a couple potential issues here.

First, you're updating a deeply nested field in that object.  Second, you are directly mutating the `medicalFiles` field.  I suspect some combination of those two issues is causing the changes to not be detected properly.

Also, that use of `Math.random()` sounds like a very bad idea.  I'd heavily encourage you to _not_ do that.

**Comment by nealoke** [comment]
@markerikson I totally agree with the `Math.random()`, this was never intended to stay ;)

Could you explain why I am directly mutating the `medicalFiles`? I'm not sure but I thought that by supplying a new object it is not mutated but replaced or am I wrong here?

Also I find it weird but does nobody have deeply nested (aka 1 level deep) fields that they update? If not please explain me how to de-nest it (but keeping the structure). If you do, how do you manage the update when it is not seen by shallow compare?

**Comment by markerikson** [comment]
@nealoke : this sequence is directly mutating the array:

```js
        const resources = Patient.withId(payload.patient).ref.resources;
	const medicalFiles = resources.medicalFiles || [];
	medicalFiles.push({name: payload.name, url: payload.url})
```

It creates another variable pointing to the _existing_ array, and then `push()` inserts an entry into that same array rather than creating a new one.  You may want to read through http://redux.js.org/docs/recipes/reducers/ImmutableUpdatePatterns.html and some of the articles at https://github.com/markerikson/react-redux-links/blob/master/immutable-data.md .

As for nestedness... yeah, it doesn't seem like _that_ uncommon of a use case.  At a minimum, I suspect you'd need to apply standard immutable update practices here if you're updating stuff that's not kept as separate related models.  That means making copies for every level of nesting, although I assume that Redux-ORM would handle copying the main "ref" object itself.

**Comment by plandem** [comment]
Don't mutate directly - you must work with models. Here example from readme:
```js
     const { Book } = sess;

    switch (action.type) {
    case 'CREATE_BOOK':
        Book.create(action.payload);
        break;
    case 'UPDATE_BOOK':
        Book.withId(action.payload.id).update(action.payload);
        break;
    case 'REMOVE_BOOK':
        Book.withId(action.payload.id).delete();
        break;
    case 'ADD_AUTHOR_TO_BOOK':
        Book.withId(action.payload.bookId).authors.add(action.payload.author);
        break;
    case 'REMOVE_AUTHOR_FROM_BOOK':
        Book.withId(action.payload.bookId).authors.remove(action.payload.authorId);
        break;
    case 'ASSIGN_PUBLISHER':
        Book.withId(action.payload.bookId).publisher = action.payload.publisherId;
        break;
    }
```

**Comment by nealoke** [comment]
@plandem thanks but how do you manage the deeper level objects within a model then?

**Comment by plandem** [comment]
What problem with deeper level? If you are working with models - its ok. But, If you working with objects directly, then you will have headache . Just work with models.
```
Book.withId(book_id).publisher.relation2.add(new Relation2(....));
```
relation2 here is relation of publisher, not book.

**Comment by chanan** [comment]
I still use something like (Pseudo code):

`Book.withId(action.payload.id).update( { deep_property: { some_prop: value }})`

And then (in reality the same line as above) I call:

`Book.withId(action.payload.id).update( { updatedAt: New Date() })`

The above works for me and the Selector gets updated. It is true that I could split out the inner object (deep_property in the above example) but I prefer not to. I have some deep and complex objects that "own" their child objects and I wold have a mess over one to one relationships that I don't want to deal with. (Basically DDD where my top level objects, entity roots, are registered in redux-orm)

**Comment by plandem** [comment]
I'm not sure it's good idea to update models indirectly. You can try of course, but I'm not sure. In v0.8 I had some issues with it, after that I refactored and working with models directly Not sure about v0.9

**Comment by plandem** [comment]
About complexity, man....trust me - more predicted state is better than some magic to decrease some **boilerplate** code. In my case I have differ ORM schemas, some models at one schema, some models at **template schema**, like: Dataset-1, Dataset-2, Dataset-3, where each **Dataset** is separate schema with own models and etc.

**Comment by chanan** [comment]
I am not updating models in directly. In my case above, deep_property is not registered in redux-orm. If it were, I would directly modify using redux_orm (Deep_propery.withId()...)

A better example might be an object such as "publisher" that has an address with a street: `Publisher.withId(1).update({ address: { street: 'My Street' }})` like I said, I could take address and make it a 1:1 relationship, but in my case I would have many of these objects that really serve no purpose.

**Comment by plandem** [comment]
> I am not updating models in directly. In my case above, deep_property is not registered in redux-orm. 

in that case it's your headache to make this updates immutable to let selectors to refresh :)

**Comment by plandem** [comment]
My main idea is - try to use ORM as much as possible and for some special cases (if you understand what are you doing) - you can't use some **workarounds** to gain something. E.g. in my case some of my models are hierarchical by nature and I could use ORM to resolve parent/children, but it's too slow for it, so I resolving it directly after **.all().toRefArray()**

**Comment by markerikson** [comment]
As far as I know, updates to the actual model contents need to follow all the normal rules of immutable updates.  If you're maintaining nested data inside that main model object, it's your responsibility to properly do copies for each level of nesting.  Redux-ORM will take care of copying the main model object and the "table" it's in.

**Comment by chanan** [comment]
> in that case it's your headache to make this updates immutable to let selectors to refresh :)

That is the problem, even when you do immutable updates (which I am), the Selector only picks up a change if it is done at the top level. That is why I added updateAt at the top level.

**Comment by nealoke** [comment]
Great to see such a conversation! About the staleness of this project, should not one person make a fork and actually maintain this project? I can see it has 11 pulls waiting -_-. Because I'm not really that good with this yet maybe @chanan or @markerikson  or @plandem ? As you said it is a good project and it makes a lot of sense to use it but it needs some updates.

I could write part of the docs!

**Comment by NE-SmallTown** [comment]
You can see this [tweet](https://twitter.com/tommikaikkonen/status/851923738522132480)

**Comment by nealoke** [comment]
@NE-SmallTown Thanks for that :) Would love to get this thing improved :D

**Comment by plandem** [comment]
@NE-SmallTown I was sure I saw you at ant-design issues :)))) This world is so small :)

**Comment by NE-SmallTown** [comment]
@plandem Ye~:smile:

**Comment by plandem** [comment]
@chanan 

> That is the problem, even when you do immutable updates (which I am), the Selector only picks up a change if it is done at the top level. That is why I added updateAt at the top level.

I hadn't test it yet, but - session holds information what model types was accessed/modifies and you can mark it manually via **markAccessed**. Probably you don't need to use timestamp - just mark nested model as accessed. But as I said - hadn't tested and don't remember internals to be sure. I would try.

**Comment by plandem** [comment]
@NE-SmallTown man, I remember time (winter 2016), when I was the only english person there and used google translate to read official docs, because I liked their code quality a lot - not every enterprise has same quality for internal code base.

**Comment by nealoke** [comment]
> I hadn't test it yet, but - session holds information about model types that were accessed/modified and you can mark it manually via markAccessed

Why are you doing dot in the `Address.modelName`? Below the source markAccessed (`session`).

```
markAccessed(modelName) {
    this.getDataForModel(modelName).accessed = true;
}
```

**Comment by plandem** [comment]
> Why are you doing dot in the Address.modelName? Below the source markAccessed (session).
Because **markAccessed** wants modelName, not model

**Comment by NE-SmallTown** [comment]
@plandem Thanks for your feedback,I think every member of antd will glad to see that it can help you.I will convey to them your feedback.And hope more people all around the world begin to use antd. :smiley: 

But here is not a good place talk to much,so please let us stop comment after this comment.

**Comment by nealoke** [comment]
@plandem I guess i'm not that smart but wouldn't you simply do `markAccessed('modelName')`?

**Comment by plandem** [comment]
@NE-SmallTown man, I'm a contributor to ant-design for a quite long time :) you can check the list of contributors :)))))

**Comment by plandem** [comment]
@nealoke 

It's up to you, but It's better do not use hardcoded values - maybe someday you will decide to change modelName and you will have to refactor.

**Comment by NE-SmallTown** [comment]
@plandem Sorry,maybe I don't say clearly.I mean I know you are a contributor,although I am not a member of antd,but I think it is a very nice library.And I see there still exist a lot of improvement need to do about the international communication because you still can see some Chinese issues.

So,that's why I say "I think every member of antd will glad to see that it does help you.I will convey to them your feedback",because your admire will encourage them to improve every aspect of antd.

And because this issue belong to redux-orm rather than antd,so I say "here is not a good place talk too much".So,if you still want to talk,you can comment on [antd's gitter](https://gitter.im/ant-design/ant-design-english).Sorry for that I won't reply anymore,because I have talk too much irrelevant in this issue.

**Comment by nealoke** [comment]
@plandem aaah okey that is clear! :D

**Comment by plandem** [comment]
If your task is solved - close the issue?

**Comment by nealoke** [comment]
@plandem will check it the coming days! If it is solved will close ofc.

**Comment by plandem** [comment]
anyway, it's not issue of ORM. you was trying to mutate ref objects directly, not model.
