### ISSUE TITLE
is it possible to emulate DB with few schemas?!

### ISSUE THREAD

**Issue by plandem** [tommikaikkonen/redux-orm#12]
E.g.:

I have Dataset (it's schema at DB) and few tables User, Location and etc.

At each dataset User/Locations and rest has own ID and they can be same for differ datasets.
E.g.:
Dataset 1:
  User 1: {id: 1, name: 'User from dataset 1' }

Dataset 2:
 User 1: {id: 1, name: 'User from dataset 2' }

So is it possible to do like this?!

**Comment by tommikaikkonen** [comment]
Hey,

If I understand you correctly, you want to use two datasets that are structured with the same schema in the same Redux application.

You can do that with Redux-ORM in the same way you can create two database instances: you can't query and modify them as a single unit if the unique keys (id) clash. If you want to use both datasets in a redux app, I suggest you have two entrypoints in your root reducer, e.g.

```javascript
{
    dataset1: schema.reducer(),
    dataset2: schema.reducer(),
}
```

Then in your selectors you need select two ORM selectors:

```javascript
const selectDataset1 = state => state.dataset1;
const selectDataset2 = state => state.dataset2;
```

Then you can use those as input selectors to the actual Redux-ORM selectors, based on which dataset you want to query.

**Comment by plandem** [comment]
it's only half of solutions, because i need to add custom login at each Model of dataset to know what dataset must be used actually.
```
class Book extends Model {
    static reducer(state, action, Book) {
        switch (action.type) {
        case 'CREATE_BOOK':
            Book.create(action.payload);
            break;
```
Will not work, because both datasets will recognize it.

Right now i'm trying to use it like this:
```
import { Schema as OrmSchema } from 'redux-orm';

class Schema extends OrmSchema {
  constructor(name = 'default') {
    super();
    this.schemaName = name; 
  }
}

export const schemaReducer = (action, model) => {
  if(model.session.schema.schemaName !== action.schema || model.modelName !== action.model) {
    return false;
  }

  if(action.type === ORM_PROCESS_RESPONSE && Array.isArray(action.records)) {
    action.records.forEach(record => {
      if(model.hasId(record.id)) {
        model.withId(record.id).update(record);
      } else {
        model.create(record);
      }
    });
  }

  return true;
};

class Dataset extends Model {
}

Dataset.modelName = 'Dataset';
Dataset.reducer = (state, action, Dataset) => {
  if(!schemaReducer(action, Dataset)) {
    return state;
  }

  console.log('schema=', Dataset.session.schema.schemaName, action.schema);
  return Dataset.getNextState();
};

```


**schemaReducer** process response from API with models (if exists) and also return flag - if it's action for same schema. And each action for model looks like this:
```
 return {
      type: ORM_PROCESS_RESPONSE,
      records: records,
      model: model.modelName,
      schema: createSchema[schema](params)
    }
```

I.e. i have to pass modelName and schemaName to use it later at reducer.

**Comment by tommikaikkonen** [comment]
Would this work?

Use the same Schema for both datasets, so working from the code in my previous response.

Then wrap your reducer like this:

```javascript
const rootReducer = (state, action) => {
    const actionDataset = action.dataset;
    const reduxOrmReducer = schema.reducer();
    return {
        dataset1: (state, action) => {
            if (actionDataset === 'dataset1') {
                return reduxOrmReducer(state, action);
            } else {
                return state;
            }
        },

        dataset2: (state, action) => {
            if (actionDataset === 'dataset2') {
                return reduxOrmReducer(state, action);
            } else {
                return state;
            }
        },
    }
};
```

So the root reducer checks the `dataset` property value in the action object, and forwards it to the corresponding reducer only if the value matches, and the other datasets are left as is.

Now if you actually want to keep `Dataset` as a model, you'd add a Dataset foreign key from each user and location to the corresponding dataset. You'd have to have a unique primary key for each User and Location across all datasets. You could do it by prefixing each User and Location id with the dataset id, then converting back when you need to communicate with the backend.

**Comment by plandem** [comment]
Well, i see your idea. I was sure i have to create schema for each reducer. Had not time to check. In my case it's a bit more difficult, because 'datasets' schema is not permanent and actually like 'async' (that's why i can't hardcode schema name at root reducer).

here is idea:
https://github.com/reactjs/redux/issues/37#issue-85098222

But i see your idea, so will refactor a bit.

**Comment by plandem** [comment]
here is my final version:
```
export function rootORMReducer(state = { }, action) {
  if (action.schema && Array.isArray(action.schema)) {
    const [ type, name ] = action.schema;
    const ormReducer = schemaTypeORM[type].reducer();
    let ormCurrentState = state[name];
    let ormNewState;

    if(action.type === ORM_API_RESPONSE && Array.isArray(action.records) && action.model) {
      const session = schemaTypeORM[type].from(ormCurrentState, action);
      const model = session[action.model];
      const idAttr = model.idAttribute;

      action.records.forEach(record => {
        if(model.hasId(record[idAttr])) {
          model.withId(record[idAttr]).update(record);
        } else {
          model.create(record);
        }
      });
      
      ormNewState = session.getNextState();
    } else {
      ormNewState = ormReducer(ormCurrentState, action);
    }

    return { ...state, [name]: ormNewState };
  }

  return state;
}
```

Everything is ok? I worry a little about:
```
ormNewState = session.getNextState();
```

Now enough information about sessions and etc.

**Comment by plandem** [comment]
i need help with 'selectors', now  i use like this:
```
const { schema } = resolveSchemaForModel(models.Dashboard);
const configSelector = state => state.builder.dashboard;
const ormSelector = state => resolveSchemaStateForModel(models.Dashboard, builderSelector(state))(state);

export default createSelector(
  ormSelector,
  configSelector,
  builderSelector,
  schema.createSelector((orm, config, builder) => {
    debugger;
    console.log('Running dashboard-settings selector. orm=');
    console.log(orm);

    let topics = [ ];
    let dashboard = { };
    
    if(orm) {
      // topics = orm.DashboardTopic.all().toRefArray();
      // dashboard = orm.Dashboard.hasId(builder.dashboard_id) ? orm.Dashboard.withId(builder.dashboard_id).ref : { };
    }
    
    // console.log('topis=', topics);
    // console.log('dashboard=', dashboard);
    
    return {
      config,
      topics,
      dashboard
    }
  })
);
```


topics not refreshing after import models as at reducer from my previous message.

**Comment by plandem** [comment]
**resolveSchemaStateForModel** returns chunk of db state - depends on Model + params. E.g.: db->adm for User model, or db->dataset-1 for Dashboard model and params {dataset_id: 1}

**Comment by tommikaikkonen** [comment]
Interesting case. I'll look into this tonight @plandem.

**Comment by plandem** [comment]
chunks for each orm state are creating runtime during 'rootOrmReducer' - i wrote it early.

**Comment by tommikaikkonen** [comment]
In your rootORMReducer, in this piece of code:

```javascript
const session = schemaTypeORM[type].from(ormCurrentState, action);
      const model = session[action.model];
      const idAttr = model.idAttribute;

      action.records.forEach(record => {
        if(model.hasId(record[idAttr])) {
          model.withId(record[idAttr]).update(record);
        } else {
          model.create(record);
        }
      });

      ormNewState = session.getNextState();
    } else {
```

If I understand correctly, you don't want to run your specified reducers for the models (`Dashboard.reducer`, `DashboardTopic.reducer` etc.) in this case -- only create the record if it doesn't exist, and get the next state based on that. You can currently do that by instantiating the session without an action ([see the internal code here](https://github.com/tommikaikkonen/redux-orm/blob/master/src/Session.js#L129)). When you call `session.getNextState()`, since the session doesn't have an associated action object, it basically just calls each Models' own `Model.getNextState()`. So the only change to that piece of code would be to not pass `action` as argument to `schemaTypeORM[type].from`. Otherwise it looks fine.

For the problem with the selector not refreshing, I'm not sure what's wrong. Based on the code, you access models Dashboard and DashboardTopic, therefore the memoize-function is checking only if the states for `Dashboard` and `DashboardTopic` have changed in the output returned by `ormSelector`. If you want to update this selector when other models have changed, then a slightly different approach is needed.

Here are some steps to help you debug the problem.

1. I've written the selector memoization algorithm in the code; you can [read it here](https://github.com/tommikaikkonen/redux-orm/blob/master/src/memoize.js#L12) and learn how it works. When you know the algorithm, reading the `memoize` code itself is pretty straightforward. That way you'll know exactly what's being checked on each call to the selector.
2. Put a `console.log` in ormSelector to see what value it's returning each time it's called. Is the state correct? Are the references (`===`) to `Dashboard` and `DashboardTopic` different from the previous calls when you want the selector to be rerun (they must be in order for the selector to rerun)?
3. If the state is updating correctly, put `console.log(orm.accessedModels)` before your return statement in the selector. It should log `['Dashboard', 'DashboardTopic']`. If not, that's a bug in Redux-ORM.
4. If all the above fails, report back; it might a bug in the Redux-ORM `memoize` function.

**Comment by plandem** [comment]
Well, i suppose i found the problem, but can't understand how to solve it. Here is log and as you see i have error at the end:
```
https://www.dropbox.com/s/9x8iy50ljb2grsb/Screenshot%202016-04-21%2013.20.46.png?dl=0
```

Error is inside of your memoize function:
```
https://www.dropbox.com/s/aoy7tnwt8lcmmlp/Screenshot%202016-04-21%2013.22.24.png?dl=0
```


Well i suppose problem is next:
1) at the start i don't have any state for ORM, because it's dynamic.
2) After '@@api/dashboardread/request ', my **rootORMReducer** import models and creates a new state in case of first time import, or update existing.


At the first selection at **createSelector** ORM state is undefined yet, so memoize can't remember accessedModels, because there is no any yet state. So it fails.

I suppose problem is because of my dynamic nature of ORM states. And i can't hardcode it from start. Looks like i must 'emulate' empty state of ORM at my ORM selector in case it's undefined.

**Comment by plandem** [comment]
looks like if my ORMSelector like this:
```
const ormSelector = state => resolveSchemaStateForModel(models.Dashboard, builderSelector(state))(state) || schema.from().reduce();
```
then everything is ok.

**Comment by plandem** [comment]
well, now i need help with that:
```
export default createSelector(
  ormSelector,
  gridSelector,
  builderSelector,
  dashTypeSelector,
  dashTitleSelector,
  schema.createSelector((orm, grid, builder, dashType, dashTitle) => {
    console.log('>>> Running grid selector...');
    // return isEqual(updatedState, state) ? state : updatedState;

    const views = orm.DashboardView.withRefs.filter({ dashboard_id: builder.dashboard_id }).toRefArray();
    console.log('accessedModels: ', orm.accessedModels);

      return 
    {
      ...grid,
      views,
      dashType,
      dashTitle
    };
  })
);

```

as you can see ** orm.DashboardView.withRefs.filter({ dashboard_id: builder.dashboard_id }).toRefArray();** will return always a new array. Is there any built-in way for this, or same recommendations as at **reselect**?
