### ISSUE TITLE
`Model.hasId` is slow

### ISSUE THREAD

**Issue by glen-nu** [tommikaikkonen/redux-orm#120]
My team attempted to load 18k objects and the app takes an incredibly long time to load. Profiling shows that `Model.hasId` is singlehandedly to blame for the performance. 

It's quite unusual because `redux-orm`  actually stores the `itemsById` in the state. So by replacing `Model.hasId` with `state.Model.itemsById`, we were actually able to get good performance again. Are there problems with checking ids this way?

**Comment by plandem** [comment]
Have no any trouble to load 10k+ items. How do you import this data?!

**Comment by tommikaikkonen** [comment]
That's weird. My guess is that a full table scan is happening instead of a O(1) check for row existence. The decision between full table scan if done here: https://github.com/tommikaikkonen/redux-orm/blob/master/src/db/Table.js#L105

If you add a breakpoint there, you should be able to see if a full table scan is being done, and if so, why that is.

**Comment by glen-nu** [comment]
With a little digging, it turns out that the id check itself is super fast. The slow step looks like `Table.accessList`, which appears to iterate through all of the items in the Table regardless of whether I'm performing an id check or not. https://github.com/tommikaikkonen/redux-orm/blob/master/src/db/Table.js#L125

Here's a screenshot from the profiler:
![image](https://cloud.githubusercontent.com/assets/24519294/25319947/288b8fe4-28d5-11e7-8f6c-aa66c532df03.png)

@plandem Because the `hasId` check is commented out in your snippet, the library is skipping the check that's making my bit so slow.
 
This probably isn't the complete issue because I'm not convinced that everyone working with 10k+ items is skipping `hasId` so maybe there's something I'm missing.

**Comment by ahutchings** [comment]
Can this issue be reopened? I am running into the exact issue @glen-nu described - a Table query to look up a row by id still performs a full table scan due to https://github.com/tommikaikkonen/redux-orm/blob/3b69f52d7abcfa5caaf98aa6c4c5396248f7882a/src/db/Table.js#L141.

**Comment by markerikson** [comment]
Don't see a mention of any PRs resolving this, so yeah, worth looking into.

**Comment by ahutchings** [comment]
I submitted PR #158 to address this issue.

**Comment by haveyaseen** [comment]
Closing as #158 has been merged.
