### ISSUE TITLE
access many-to-many field is not as documented?

### ISSUE THREAD

**Issue by constantx** [tommikaikkonen/redux-orm#122]
I have a Group Model:

```js
Group.fields = {
  id: attr(),
  name: attr(),
  published: attr(),
  type: attr(),
  locale: attr(),
  products: many('Product'),
}
```

and a Product Model:

```
Product.modelName = 'Product';

// Declare your related fields.
Product.fields = {
  id: attr(),
};
```

When creating a new group and passed in the `products` array, the relationship seems to be created based on the state shown:

<img width="461" alt="developer_tools_-_http___localhost_5000_explore" src="https://cloud.githubusercontent.com/assets/113969/25313164/b0307662-2853-11e7-90a7-67ce98498807.png">

However, when I'm trying to access the `products` field on the `Group` instance, it's not there :(

The needed array of products for the group seems to reside on `groupproductSet` key on the group instance, not the `products` key as I expected. Is this by design?

<img width="955" alt="developer_tools_-_http___localhost_5000_explore" src="https://cloud.githubusercontent.com/assets/113969/25313194/52ac321e-2854-11e7-9bcc-d1f74d792457.png">

**Comment by constantx** [comment]
hmm, actually. the `groupproductsSet` is the `products` array I'm expecting either…

So confusing with the documentation.

**Comment by tommikaikkonen** [comment]
Thanks for opening the issue! Looks like the problem is that the `groupproductsSet` is joined correctly (finding the rows in the through table associated with `g`), but the latter join from `GroupProducts` to Product is failing. The latter join happens here https://github.com/tommikaikkonen/redux-orm/blob/master/src/descriptors.js#L118 - are you able to debug what happens there?

You should note that [withRefs](https://github.com/tommikaikkonen/redux-orm/blob/master/src/QuerySet.js#L268) is deprecated in the newest version `0.9.0-rc.3`. You can have a look at [the migration guide for more information](https://github.com/tommikaikkonen/redux-orm/wiki/0.9-Migration-Guide).

**Comment by constantx** [comment]
So I found the issue. 

In the model reducer, I pass the whole product object (part of the group) during the Session.Group.create steps. I assume when passing the whole product object into the group, the Product model will also take care of the creation of the object. 

I had to remap to only keep the products IDs in the group object, and create the products separately via the Sesssion.Product.create(), the relationship and query works.

> You should note that withRefs is deprecated in the newest version 0.9.0-rc.3. You can have a look at the migration guide for more information.

Ya, I've switched to `toRefArray()`. Thanks for the headsup :)

**Comment by constantx** [comment]
> In the model reducer, I pass the whole product object (part of the group) during the Session.Group.create steps. I assume when passing the whole product object into the group, the Product model will also take care of the creation of the object.

Should it be the case? I thought I read somewhere in the documentation that when passed a whole object on the linked model, that model will automatically take care of creating that it in the related model?

**Comment by constantx** [comment]
Also, is it possible for a field to have a `many` relationship with its own model? Use case is that we want to link related products to a particular products.

**Comment by plandem** [comment]
try a new version
