### ISSUE TITLE
One to many

### ISSUE THREAD

**Issue by guillaumepotier** [tommikaikkonen/redux-orm#125]
Hi there,

How would you represent `OneToMany` relations with redux-orm? I'm hesitating between using `many` (which is falsy) or `fk`.

In my case, I have a `Meeting` entity that could contain `Message` entities. I could either do

```
Meeting
messages: many('Message', 'meeting') // strange meeting here

Message
user: fk('User', 'messages')
```

```
Meeting

Message
meeting: fk('Meeting', 'messages')
user: fk('User', 'messages')
```

What case would be better?

Thanks for your help

**Comment by guillaumepotier** [comment]
By reading the doc further, it seems the right solution is the second one with the two `fk()`. If I understand correctly, `fk` is strictly equivalent to `oneToMany`, this is not obvious at first glance.

I also had a lot of difficulties to find how to correctly use selectors in 0.9 with props and found the solution in another issue.

I'll try to make some PRs to update the doc and make things easier to understand.

**Comment by arteniioleg** [comment]
I'm having hard times making it work.

1. There are no code examples
2. Not sure on which side to place `fk()` (owning or child)
3. Will `session.Meeting.upsert({id: 'meeting', messages: [{id: 'message'}]})` update the messages too or I should loop manually and `upsert()` each message?
