### ISSUE TITLE
[Question]About selector and model create

### ISSUE THREAD

**Issue by NE-SmallTown** [tommikaikkonen/redux-orm#128]
Have talked with mark in the [reactiflux](https://discordapp.com/channels/102860784329052160/103696749012467712)

I think there is still 2 questions:

1.It seems like that we need do all things like we do in the traditional react app with reselect,but I think we have set the relationship by fk or many,I think redux-orm knows this,so it can help us to get our data which we need,we don't need to something like

```
createOrmSelector(session => {
  const arr = session.SomeModel.withId(someId).toModelArray(); 

  arr.map(item => ({
     ...item,
     otherModel: item.otherModel.map(id => session.otherModel.with(id))
  }))
})
```

I hope just call session.SomeModel.withId(id) can complete all of these,but actually it can't,what's your thought about this?

2.I notice that redux-orm doesn't create Model instance automatically for fk field.i.e. if Model Book has a fk field Author,when dispatch the 'create-book' action and then I need to pick something1 from action.payload,and then call  Book.create(something1).

But redux-orm won't create Author instance in the orm reducer,it needs me to create in the Author model's reducer method(receive 'create-book' action and pick something2 from action.payload,and then call the Author.create(something2)),this is too tiring, I think redux-orm can/should do this and this is it's responsibility

cc @plandem  @chanan @NathanBWaters @tiii

**Comment by nealoke** [comment]
No explanation why it is closed? :)

**Comment by NE-SmallTown** [comment]
Sorry, because there is no further discussion
