### ISSUE TITLE
[Question] Getting model reference

### ISSUE THREAD

**Issue by bouncehead13** [tommikaikkonen/redux-orm#137]
I'm looking to understand the reasoning behind the behavior when getting the reference of a model.

Let's say we have a Product that we are selling and each product has many variants. The model I have outlined looks like this.
```
class Product extends Model {}

Product.modelName = 'Product';

Product.fields = {
    id: attr(),
    name: attr(),
    variants: many('Variant', 'product')
};
```

If I were to get the first product and ask for the reference, variants are not returned in the object.
```
session['Product'].first().ref => { id: 0, name: 'Test Product' }
```

What I was expecting to see would have been something like this
```
{
    id: 0,
    name: 'Test Product',
    variants: [
        {...},
        {...}
    ]
}
```

Why are the variants not returned when asking for the reference of the model? Any insight is much appreciated!

**Comment by plandem** [comment]
**ref** is a vanilla js object that holds info. You need to work with model, not reference

**Comment by bouncehead13** [comment]
For some more context, I am working with AngularJS which relies on references so working with the model, while might offer more detail, returns a copy of everything.

I guess what I'm hearing is, there's nothing I'm missing, but simply getting the `ref` won't return nested objects. Is that correct thinking?

**Comment by markerikson** [comment]
Yes.  Redux-ORM's `Model` classes act as facades around the plain JS objects in a Redux store's state.  A `Model` class instance knows how to dereference the relations appropriately, so `someModel.someRelation` will look up the right item in the other "table" within the state.  However, `someModel.ref` gives you the actual plain JS object within the store state, so there's no dereferencing going on from there.

**Comment by bouncehead13** [comment]
I was afraid you were gonna say that. It feels like a limitation to how `.ref` works. I don't know if you would consider this, but adding an optional param `.ref(true)` to dig deep into the models and return "everything" it knows about. Almost like `someModel.someRelation` would also be evaluated for a reference.

Regardless, thanks for confirming the expected behavior when getting a `.ref`.

**Comment by plandem** [comment]
Sorry, but I can't get why you can't use model, instead of ref.

**Comment by markerikson** [comment]
@bouncehead13 : you seem to be mixing up the intended use cases.

`ref()` is explicitly for returning a reference to the underlying JS object in the store.  The `Model` instance is for handling the relations.  

Models define JS getter fields for each known attribute and relation, and when you access `someModel.someRelation`, the getter logic looks up the correct relation and returns an instance of the right `Model` subclass that wraps _that_ plain JS object.  Dereferences are done on-demand.  If I access `someModel.someRelation.anotherRelation.thirdRelation`, each of those dereferences is done right there.

So, if anything, what you'd actually want is something like `MyModel.withId(id, {dereferenceEverything : true})`.  Asking for `someModel.ref(true)` doesn't make any sense conceptually.

Can you give some more information on what it is you're actually wanting to accomplish?

**Comment by bouncehead13** [comment]
Everything both @plandem and @markerikson have said makes sense. Let me outline the scenario with the problem I'm facing. Just to preface, the project is written using AngularJS.

The model
```
class Product extends Model {}

Product.modelName = 'Product';
Product.fields = {
    id: attr(),
    name: attr(),
    variants: many('Variant', 'product')
};
```

The controller
```
this.product = session.Product.first().ref; // using the reference
```

The view
```
<p>{{ $ctrl.product.name }}</p>
<div ng-repeat="variant in $ctrl.product.variants"</div>
```

As I understand now, `.ref` does not return the variants so the view is missing all variants. I can make the view work by using the model itself instead (with some small tweaks to the code which I'm not going to write up here).

The problem...let's say I want to add an additional variant to the Product like such
```
this.product = session.Product.first(); // using model instead
this.product.variants.add(<variant model here>);
```

Because `this.product` is a copy and the view is bound to that variable, the view will not show the additional variant that just got added. Without using the reference, how would I update the view to display the new information? I was reading up on `createSelector` and maybe that might work. I have yet to try implementing with that.

Does this scenario make sense? Hopefully!

**Comment by plandem** [comment]
Now I see. The name of library - redux-orm , so its working in same way. It's better for you to find more info about angular+redux. After that you will answer on your question by self :)

**Comment by bouncehead13** [comment]
Fair enough @plandem. The API for redux-orm is so easy to use! Was hoping for the "secret sauce" to make this work with AngularJS. I'll continue to do more research. Thanks!
