### ISSUE TITLE
Many() relationship with own model

### ISSUE THREAD

**Issue by kmrachko** [tommikaikkonen/redux-orm#144]
Hello, could you help me? I'm facing an issue about many-to-many relationship with own model. What I need is to model **User** have a list of _subscribers_ and people who are _subscribed_ to them. I was thinking of this solution:
```javascript
User.fields = {
  id: attr(),
  name: attr(),
  photo: attr(),
  birthdate: attr(),
  subscribed: many('User', 'subscribers'),
};
``` 
However, it produces this error: [Screenshot](https://drive.google.com/open?id=0BwDj6sgovEnzaUFUX2lRU1MxdHc)
Would be really grateful for you time and help. Thanks for the awesome work!

**Comment by plandem** [comment]
Look for previous issue about tree - same way. Use 'fk', not 'many'

**Comment by kmrachko** [comment]
I did, but if I understood right, fk is one-to-many relationship. And that way I will get User with many subscribers and only one model to which he subscribed. However, I need both many subscribers and many models to subscribe on.

**Comment by plandem** [comment]
oh, I see now.  Hmm, need to check the code - didn't use like this. Can you try to describe relation with explicit **through** model?!

**Comment by kmrachko** [comment]
Will try, if I understood you right. As I see it now, User model should look like this:
```javascript
User.fields = {
  id: attr(),
  name: attr(),
  photo: attr(),
  birthdate: attr()
}
```
And through model like this:
```javascript
UserSubscription.fields = {
  from: fk('User', 'subscribedTo'),
  to: fk('User', 'subscribers')
}
```
That's my idea about resolving this issue, would be glad to hear other opinions.

**Comment by plandem** [comment]
so...does it help?

**Comment by kmrachko** [comment]
Not tested yet, but it should. However following code line `subscribed: many('User', 'subscribers')` seems a more elegant solution to the described problem and if it's possible, it would be nice to go without through model mentioned earlier. The question is simply: does redux-orm support many-to-many relationship with the same model and if not, could it be included in the roadmap for the 1.0 version?

**Comment by plandem** [comment]
**many** is using  through model under the hood. You just need to set it explicit, because it's not possible to automatically resolve **fk** fields in your case: same model - what is **from** and what is **to*?!

```
const UserModel = class extends Model {};
UserModel.modelName = 'User';
UserModel.fields = {
	id: attr(),
	name: attr(),
};

const User2TeamModel = class extends Model {};
User2TeamModel.modelName = 'User2Team';
User2TeamModel.fields = {
	user: fk('User'),
	team: fk('Team'),
};

const TeamModel = class extends Model {};
TeamModel.modelName = 'Team';
TeamModel.fields = {
	id: attr(),
	name: attr(),
	users: many({
		to: 'User',
		through: 'User2Team',
		relatedName: 'teams',
		throughFields: ['user', 'team'],
	}),
};
```

**Comment by CharlesBradshaw** [comment]
@plandem I implemented the "through" and got a self referencing many to work! 
`export class Entity2EntityModel extends Model {};
Entity2EntityModel.modelName = 'Entity2Entity'
Entity2EntityModel.fields = {
  parent: fk('Entity','child'),
  child: fk('Entity','parent'),
}

export class Entity extends Model {}
Entity.modelName = 'Entity'
Entity.fields = {
  id: attr(),
  Parents: many({
    to:'Entity',
    through: 'Entity2Entity',
    relatedName: 'Children',
    throughFields: ['child','parent'],
  }),
}`
