### ISSUE TITLE
Using selectors in models?

### ISSUE THREAD

**Issue by augustbjornberg** [tommikaikkonen/redux-orm#146]
I've tried importing selectors in models, but ran in to a heap of trouble. It looks like createSelector breaks because things are being set up in the wrong order. Is selectors in models something that isn't supported? Note that i didn't try to execute the selector, simply import it. 

**EDIT: Code.**
It might also be hugely helpful for me and others if orm-redux-primer had an example of models using selectors.

Model.js, line 5 with the selector is what breaks everything
https://gist.github.com/augustbjornberg/ea97667d419d074aaf4e75050f4664db

Selectors.js
https://gist.github.com/augustbjornberg/53611860a64b7e49affc023e11182404

Orm.js
https://gist.github.com/augustbjornberg/3bf44091af6464d72daffb13a915d262

Store.js
https://gist.github.com/augustbjornberg/aaf955487753b73221959db5d1e1bff7

<img width="375" alt="screen shot 2017-07-04 at 12 05 58 pm" src="https://user-images.githubusercontent.com/1137612/27840843-55d55ae8-60b1-11e7-8792-baaf80f9b419.png">

**Comment by markerikson** [comment]
Yeah, it's hard to say something without actually seeing your code.

**Comment by augustbjornberg** [comment]
Updated post with links to code

**Comment by markerikson** [comment]
BTW, as a side note, you can put multiple files in one gist :)

**Comment by markerikson** [comment]
Hmm.  So, on the one hand, I really haven't actually tried to use selectors with Redux-ORM much yet, and I definitely haven't used Redux-ORM's `createSelector` function.  On the other hand, I don't think I understand what exactly is breaking based on those snippets and the stack trace.

You say that models.js line 5 is the issue:
`import {activePack} from 'TruthOrDrink/src/redux/selectors'`

Unfortunately, I don't see how that correlates with an error message of "cannot read property 'session' of undefined", or why just importing that selector function would cause a problem.

**Comment by plandem** [comment]
I still can't understand what do you "createSelector in a model ".
