### ISSUE TITLE
Suggestion -- Move towards Typescript

### ISSUE THREAD

**Issue by jmenestr** [tommikaikkonen/redux-orm#151]
I'm not sure what your thoughts are on on typescript, but I'd love to see this project have a TS version. I think relational models are great candidate for types and considering a lot of new react/redux projects are now using TS, I think it would be useful.

I'm totally willing to take this up as well. If this is something that's of interest I'd love to discuss it.

**Comment by NathanBWaters** [comment]
I'm a fan of any form of static type checking in our code base!  After doing some research, I agree that Typescript is the way to go. 
@jmenestr perhaps work off of this pull request? 
https://github.com/tommikaikkonen/redux-orm/pull/46

**Comment by plandem** [comment]
I would like to have v1 in TS, but not sure will have enough time to rewrite from ground :(

**Comment by markerikson** [comment]
I'd suggest we not go there for v1.  Make sure things are stable, add any other features we think are _really_ important, and get v1 working great and shipped.  Then we can investigate rewriting it in TS.

**Comment by Aryk** [comment]
Hey guys, just curious, what exactly does this mean over and above having accurate and up-to-date TS type definitions? Does it mean fixing some items like [this](https://github.com/tommikaikkonen/redux-orm/issues/68)?

**Comment by haveyaseen** [comment]
Closing this, please refer to @keenondrums' repo.
We will not integrate TypeScript into the repo, at least not in the near future. See the discussion in #168.
