### ISSUE TITLE
How can I add a custom property to a Model?

### ISSUE THREAD

**Issue by jordan-enev** [tommikaikkonen/redux-orm#152]
Let's say that I'm having a lot of Books. Before displaying them somewhere, first I have to fetch them via the API. While waiting for the API response, I want to display a loading message.

Before start using redux-orm, I did it as adding `isFetching` property in the Books store and later toggle it via reducers. Here is how a Store entity looks like:

```javascript
// Store
books: {
  byIds: {},
  allIds: [],
  isFetching: true
}
```

**How can I achieve that in redux-orm?**

I made it working in the following immutable fashion, but I'm not sure about the performance. Imagine if we have a lot of Models and copying all of them sounds like a bad decision:

```javascript
import orm from './orm'

export default function ormReducer(dbState, {type, payload}) {
  const sess = orm.session(dbState);

  // Session-specific Models are available
  // as properties on the Session instance.
  const { Books } = sess

  switch (type) {
    case 'FETCH_BOOKS':
      sess.state = {...sess.state}
      sess.state.Book.isFetching = true

      break
    case 'RECEIVE_BOOKS':
      payload.data.map(book => Book.create(book))
      sess.state.Book.isFetching = false

      break
  }

  return sess.state;
}
```

**Comment by NathanBWaters** [comment]
You can still use your paradigm of `isFetching` by adding that as one of your fields on your `Book` model.  By expanding the sample code for example:
```
// models.js
import {fk, many, attr, Model} from 'redux-orm';

class Book extends Model {
    toString() {
        return `Book: ${this.name}`;
    }
    // Declare any static or instance methods you need.
}
Book.modelName = 'Book';

// Declare your related fields.
Book.fields = {
    id: attr(), // non-relational field for any value; optional but highly recommended
    name: attr(),
    authors: many('Author', 'books'),
    publisher: fk('Publisher', 'books'),
    isFetching: attr(),
};
```

**Comment by jordan-enev** [comment]
@NathanBWaters  thanks for the support!

Unfortunately, adding it to a model doesn't suit us, because the inital state of the Book store is as follows (be redux-orm design):

```javascript
Book: {
  items: [],
  itemsById: {},
  meta: {}
}
```
Therefore we don't know whether the Books are being fetched, or there aren't any books.

If we have `isFetching` flag, as I mentioned in the question, then:

1. We know that the Books are being fetched and we can show a loader.
```javascript
 if (Book.isFetching) return <div>Loading ... </div>
```
2. We know that we tried to fetch the Books, but there weren't any Books returned from the API, so we can display a 'There aren't any books' message` 
```javascript
 if ( ! Book.isFetching && ! Book.items.length) return <div>No data.</div>
```

**Comment by tiii** [comment]
I don't think this is possible with redux-orm. But since you are using a custom reducer anyways, you could just move the isFetching state to a seperate reducer and just reuse the FETCH_BOOKS and RECEIVE_BOOKS actions.

**Comment by jordan-enev** [comment]
@tii thanks for the suggestion! That was one of my first ideas, before opening the issue.

I skipped it on a purpose, because I prefer everything to be organized by a context in one single place. Also there will be a little more bootstrapping code, each time I'm creating a Model. 

I'm wondering whether @markerikson has some ideas.

**Comment by markerikson** [comment]
Sorry, no particular ideas here :(

**Comment by markerikson** [comment]
@DisaPadla : honestly, it's not something I've had to worry about in my own apps.

**Comment by haveyaseen** [comment]
@jordan-enev @DisaPadla Storing UI state is definitely not in the scope of redux-orm. What @tiii said makes a lot of sense to me, try to store it either in a separate reducer (which you change by `dispatch`ing actions and read using Redux' `mapStateToProps`) or, albeit not DRY conformant, in a component's state (which you change using `setState`).

It is further a bad idea to hook into the private API/members of `session` or `session.state`. This will likely hurt you in the long run.

Closing as out-of-scope (and actually quite easy to solve -- as suggested by @tiii).

**Comment by z0al** [comment]
This is pretty old, but I will write this here in case anyone finds it useful.

Currently `redux-orm` represents the state like this:

```javascript
{
  ModelName: {
    items: []
    itemsById: {},
    meta: {}
  }
}
```
 I'm not sure if it's ok to write data to Model's meta, but here is what I'm doing right now (might be a hack, but a clean one)

I have a base model for all of my models:

```javascript
class BaseModel extends Model {
  // Writes to this model's meta
  static updateMeta(state, ownMeta) {
    const model = state[this.modelName];

    return {
      ...state,
      [this.modelName]: { ...model, meta: { ...model.meta, ...ownMeta } }
    };
  }

  // ... some other app-specific stuff

}
```

Then we make our `Book` model extends the BaseModel

```javascript
class Book extends BaseModel {}
```

We can now store as much meta as we like in this way:

```javascript
function reducer(state, action){
  const sess = orm.session(state)
  const { Book } = sess

  switch(action.type){
    case 'FETCH_BOOKS':
      // do other stuff
      return Book.updateMeta(sess.state, {isFetching: true})
    case 'RECEIVE_BOOKS':
      // do other stuff
      return Book.updateMeta(sess.state, {isFetching: false})
  }
}
```
