### ISSUE TITLE
Using many throws me the following error: Uncaught TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by danielbokor** [tommikaikkonen/redux-orm#160]
Hi,

I'm trying to use redux-orm for a project that for now is going to include two entities, Elements and Animators. I want to achieve a many relationship. I have the following within models:

**/models/Element.js**

        import { fk, many, attr, Model } from 'redux-orm';
        import propTypesMixin from 'redux-orm-proptypes';
        import { ELEMENT } from '../actions/constants';
    
        const ValidatingModel = propTypesMixin(Model);
    
        export default class Element extends ValidatingModel {
            static reducer(action, Element, session) {
                const { payload, type } = action;
                switch (type) {
                    case ELEMENT.SET_ELEMENT:
                        Element.create({
                            name: payload.name,
                        });
                        break;
                    default:
                        break;
                }
            }
        }
    
        Element.fields = {
            id: attr(),
            name: attr(),
        };
    
        Element.modelName = 'Element';

`

and in **/models/Animator.js**

        import { fk, many, attr, Model } from 'redux-orm';
        import propTypesMixin from 'redux-orm-proptypes';
        import { ANIMATOR } from '../actions/constants';
        
        const ValidatingModel = propTypesMixin(Model);
        
        export default class Animator extends ValidatingModel {
            static reducer(action, Animator, session) {
                const { payload, type } = action;
                switch (type) {
                    case ANIMATOR.SET_ANIMATOR:
                        Animator.create({
                            name: payload.name,
                            element: session.Element.withId(0),
                        });
                        break;
                    default:
                        break;
                }
            }
        }
        
        Animator.fields = {
            id: attr(),
            name: attr(),
            element: many('Element', 'animators'),
        };
        
        Animator.modelName = 'Animator';

within **/models/index.js** 

        import { ORM } from 'redux-orm';
        import Element from './Element';
        import Animator from './Animator';
        import { proxyClassForORM } from './proxy';
        
        const orm = new ORM();
        orm.register(
            proxyClassForORM(Element),
            proxyClassForORM(Animator),
        );
        
        export default orm;

and in **/reducers/index.js**

        import { combineReducers } from 'redux';
        import { createReducer } from 'redux-orm';
        import { routerReducer as routing } from 'react-router-redux';
        import orm from '../models';
        import ApplicationReducers from './Application';
        
        export default combineReducers({
            ...ApplicationReducers,
            orm: createReducer(orm),
            routing,
        });

Because I defined a `many` relations within `Animators`, when `Animators.create({ [...] })` is called, I get the following error:

        TypeError: values.map is not a function
            at eval (Model.js?228a:232)
            at Array.forEach (<anonymous>)
            at Animator._refreshMany2Many (Model.js?228a:227)
            at Function.create (Model.js?228a:340)
            at Function.create (index.js?950d:120)
            at Function.reducer (Animator.js?d8ec:28)
            at eval (redux.js?1ee6:18)
            at Array.forEach (<anonymous>)
            at defaultUpdater (redux.js?1ee6:15)
            at eval (redux.js?1ee6:27)

This is what my store looks like: https://imgur.com/a/8ESD5

There might be something I missed, but I can't figure out what. Any ideas? @tommikaikkonen

In case it matters, here's my .babelrc

    {
      "presets": [
        ["env", {
          "targets": {
            "node": "current"
          }
        }],
        "react"
      ],
      "plugins": [
        "transform-async-to-generator",
        "transform-object-rest-spread",
        [
          "transform-class-properties",
          {
            "loose": true
          }
        ]
      ]
    }

Thanks,
Daniel

**Comment by danielbokor** [comment]
Update: I've found the issue, I was passing to Animator.elements an integer instead of an array. However, in the state the AnimatorElement through Model did not update: https://imgur.com/a/Qdtyi

**Comment by sapjax** [comment]
```
Animator.create({
    name: 'My sample animator',
    elements: session.Element.withId(0).id,
});
```
should be:
```
Animator.create({
    name: 'My sample animator',
    element: session.Element.withId(0).id,
});
```
