### ISSUE TITLE
What is schema?

### ISSUE THREAD

**Issue by smiled0g** [tommikaikkonen/redux-orm#164]
In the README, under **[Use with React section](https://github.com/tommikaikkonen/redux-orm#use-with-react)**, there's `./schema` import which couldn't be found anywhere in the doc. I assume it is already deprecated? If so, what's the new way of using **Selector**?

**Comment by yvanwangl** [comment]
Yes, Schema has been deprecated. you can use import {ORM} from 'redux-orm'.
