### ISSUE TITLE
When to support Typescript?

### ISSUE THREAD

**Issue by yvanwangl** [tommikaikkonen/redux-orm#168]
First, very grateful for your work! This is an awesome library and i love it so much.
But, i find it not support typescript, i feel a little lost.
So, when to support typescript?
thank you!

**Comment by keenondrums** [comment]
@yvanwangl I've just created TypeScript definitions for redux-orm. Check it out here https://github.com/keenondrums/types-redux-orm

**Comment by yvanwangl** [comment]
@keenondrums Thanks for your work! I will try it later!

**Comment by yvanwangl** [comment]
@keenondrums The npm package works well, thank you again for your work!

**Comment by Aryk** [comment]
@haveyaseen not sure if you use typescript. I have some definitions (might be different than @keenondrums).

If we can verify that they work with 0.10, can we maybe merge them in too?

**Comment by haveyaseen** [comment]
@Aryk I don't use Typescript and I have practically 0 knowledge about it. Can we make sure that they work using automated tests? My fear is that this will cause too much maintenance overhead...

**Comment by Aryk** [comment]
Typescript is 100% decoupled from the function of the library. It is a separate file and cannot get in the way of the current tests, functionality or performance the library. It is a "index.ts" file that gets picked up by applications using typescript. You could have a completely screwed up typescript file and it cannot break the library (but will throw weird typescript errors for TS users), it's purely there to help developers using typescript when developing their apps.

**Comment by haveyaseen** [comment]
Then I'm happy to merge any TypeScript definitions, provided there is an easy way to turn off these errors for TypeScript developers. Would be very awful to break things for people everytime we make a release, and then to re-release as fast as possible to fix broken TypeScript definitions.

**Comment by haveyaseen** [comment]
@markerikson suggested in #151 not to include TypeScript definitions before v1. Don't know how far that makes sense and I would love to know his reasoning.

**Comment by markerikson** [comment]
My comment was about rewriting the code using TS, not about type definitions.

That said, over in the main Redux repos, we're about to switch from shipping type definitions with the libs themselves, to having them be separate and over in the DefinitelyTyped repo.  Tim Dorr and I aren't TS experts (I don't use TS at all, and Tim has just played with it a bit), and so we don't have the time or expertise to keep fiddling with the type definitions.  It's better if the community can work on those themselves.

**Comment by Aryk** [comment]
Got it, ok, let's keep it in the TS definitions repo.

**Comment by haveyaseen** [comment]
Alright, exactly what I feared as well. So yeah, I'm happy with leaving it outside.
