### ISSUE TITLE
ImmutableJS

### ISSUE THREAD

**Issue by silentlight** [tommikaikkonen/redux-orm#171]
Hello!

I was wondering if there is a way to use redux-orm together with immutablejs?

Thanks

**Comment by markerikson** [comment]
I thought there was an issue in this repo where I had specifically answered that question, but I don't see one.  Closest I see is #82 .

I believe the answer is "no".  Redux-ORM assumes that you're using plain JS objects and arrays in your store.

**Comment by yvanwangl** [comment]
@silentlight I am afraid not. I'm agree with @markerikson .  Redux-ORM use JS plain object while immutablejs is not.
