### ISSUE TITLE
[Question] How to split DB state into multiple reducers

### ISSUE THREAD

**Issue by miguelrs** [tommikaikkonen/redux-orm#174]
(I'm rather new to react/redux - sorry if this is a dumb question)

I have an existing app using react native and redux (still in early dev stage), and I'm trying to refactor it to use redux-orm.  

The code is divided into "modules", each one with its own reducer (and its own models, selectors, components,...)  
Each reducer is in charge of a part of the state, and then I use `combineReducers` to create a root reducer.  

```
// rootReducer.js
export default combineReducers({
    books: books.reducer, // I want to use ORM here.
    authors: authors.reducer, // I want to use ORM here.
    nav: navigation.reducer,
});
```

As far as I understand from the docs, (if not following the approach of reducers as static methods of models) Redux ORM works with just one reducer to manage all the DB state, is that correct?  
i.e., you can still use `combineReducers` to have other reducers for things like navigation, forms, or whatever, but all the stuff to deal with "DB entities" must be in a single reducer...

I saw issue #17, which seems to be related, but I don't really understand the solution there...

**Comment by miguelrs** [comment]
Basically, I'd like to know whether the approach explained in this section of Redux docs is applicable with Redux ORM.

[Redux docs: Separating data handling by domain](https://redux.js.org/docs/recipes/reducers/RefactoringReducersExample.html#separating-data-handling-by-domain)

As far as I understand, this is not possible since the "slice" of the state that is managed by the ORM must contain all the models...

```
// this is the whole state...
{
    orm: {/* this needs to contain all the models */},
    otherSlice: {/* you can still have separate state, but not handled with ORM */}
}
```

You can also factor out the logic to handle actions to separate "case reducers", which afaik can use ORM, but again, all the models state needs to go into the same "slice"...  

Is this correct?

**Comment by markerikson** [comment]
@miguelrs : you could certainly have multiple "entities" slices in your app's state if you wanted.  Admittedly, this is a use case I haven't had to deal with yet, so I don't have any real answers on this one.

**Comment by miguelrs** [comment]
When you say I could, do you mean I could with the existing Redux-ORM?  
The only way I can think of is creating one instance of ORM per slice - I'm not even sure it'd work, but doesn't feel right...

Anyway, assuming I have all the models in one slice, how can I structure a big app without having a massive "module"?   
(by "module" I understand a place where I put components, reducer, selectors, actions, etc. related to a part of the system).

--- 

E.g., imagine I have an app to manage a library, with 2 main parts:  
- the book catalogue, with models like `Book` and `Author`. I need to be able to query for books in lots of different ways, and also add/modify/delete books/authors in multiple ways - this requires many selectors, many actions and a complex reducer.  
- the book lending stuff, with models like `Member` and `Loan`. Again, there's lots of actions and selectors required to manage all this.

In this scenario, I'd have 2 "modules", so I'd separate my state in 2 slices, and would have one reducer for each part, and also will have the selectors and actions separated for each module.

How would I structure this using Redux-ORM? Is it normal practice to put all this stuff in a single module?

**Comment by markerikson** [comment]
Yes, my answer was picturing having multiple ORM instances, and multiple "DB slices".

If you look at my ["Practical Redux" series](http://blog.isquaredsoftware.com/series/practical-redux), I show some examples of ways to write generic CRUD-type behavior for different model classes stored in Redux-ORM, as well as feature-specific reducer behavior.  You might want to read through that and get some ideas.

Are you picturing code-splitting these different "modules", or just trying to maintain encapsulation?

**Comment by markerikson** [comment]
@miguelrs : Part of the issue here is that you're trying to treat all of these "modules" as being completely encapsulated for each other.  At _some_ point, parts of this have to get combined into something the application as a whole can understand.  If different "modules" require data from each other, then yes, either you have to have higher-level logic that wraps them up and injects the data they need, or they just know that the other modules exist and import the parts they need.

Afraid I don't have time to answer this in more depth right now.

As for the `session.reduce()` thing, that's because most of the blog posts were written using the Redux-ORM 0.8 API, and 0.9 changed things.  See [Practical Redux Part 9](http://blog.isquaredsoftware.com/2017/07/practical-redux-part-9-managing-dependencies/) for details on the changes.

You might want to drop by the Reactiflux chat channels at some point.  I may have time to discuss this further later this week.

**Comment by miguelrs** [comment]
Thanks a lot for taking your time to answer - yes you're probably right, I think I can work a bit around that approach in my previous post to be able to separate things quite nicely 👍   

(I'm closing this as this is not really an issue)
