### ISSUE TITLE
Flow type definitions

### ISSUE THREAD

**Issue by B-Reif** [tommikaikkonen/redux-orm#178]
I'm working on a flow type definition to submit to [flow-typed](https://github.com/flowtype/flow-typed). I have a few uncertainties, so I'm reaching out to ask for some help in typing redux-orm.

Here's the gist of what I'm working on: https://gist.github.com/B-Reif/772bdb132dc9597f1a014d15707167ba

Some questions/thoughts:

- How should we type the Model's [ref attribute](http://tommikaikkonen.github.io/redux-orm/Model.js.html#line410)? Should it be left up to the user & their inheriting classes?
- How should we type `createSelector`? I have an existing definition in this gist, but it's not a sufficient description. I imagine it should be quite similar to [reselect's type definition](https://github.com/flowtype/flow-typed/blob/master/definitions/npm/reselect_v2.x.x/flow_v0.28.x-/reselect_v2.x.x.js). (It's a little scary-looking but AFAIK the only way to type this kind of function signature.)
- @keenondrums recently contributed a [TypeScript definition](https://github.com/keenondrums/types-redux-orm/blob/master/redux-orm/index.d.ts). It has a few unsafe types under TODOs, but some of what's there can be used as a basis for flow typing.

**Comment by markerikson** [comment]
Great!  You may also want to compare with this Flow types gist from @ahutchings : https://gist.github.com/ahutchings/357001da662addb30e45e15fe87206e2 .

Not sure on answers to your questions, though.

**Comment by B-Reif** [comment]
I've definitely considered that gist. It's a reasonable skeleton, but it has many unsafely typed fields.

**Comment by B-Reif** [comment]
Would we be interested in actually adding Flow typing to the source code? I started a contribution for something else in #185 and found it to be kind of challenging without knowing any typing information.

**Comment by haveyaseen** [comment]
Unless someone is willing to keep `Flow` types up-to-date I think we cannot support this officially. Would probably cause more harm than good to have outdated metadata in shipped code.
