### ISSUE TITLE
Remove the need to manage related models

### ISSUE THREAD

**Issue by rogic89** [tommikaikkonen/redux-orm#179]
First of all, I love the lib, you guys did an amazing job, I use it in my app widely and its working great!

This is an enhancement and not an issue.

What I noticed is the need to properly manage related models when creating/deleting/refetching a new Model record. Which is sometimes not as easy given the data received from API, not to mention it brings a lot of, probably, unnecessary code.

example:

**InventoryItem Model**
```
import { fk, many, attr, Model } from 'redux-orm';
import types from 'redux/types';

export default class InventoryItem extends Model {

  static get fields() {
    return {
      id: attr(),
      category: fk('InventoryCategory'),
    };
  }

  static reducer(action, InventoryItem, session) {
    switch (action.type) {
      case types.CREATE_INVENTORY_ITEM_SUCCESS : {
        InventoryItem.create(action.data);
        break;
      }
    }
  }
}

InventoryItem.modelName = "InventoryItem";
```

**InventoryCategory Model**
```
export default class InventoryCategory extends Model {

  static get fields() {
    return {
      id: attr(),
      items: many('InventoryItem')
    };
  }

  static reducer(action, InventoryCategory, session) {
    switch (action.type) {
      case types.CREATE_INVENTORY_ITEM_SUCCESS : {
        InventoryCategory.withId(action.data.category).items.add(action.data.id);
        break;
      }
    }
  }
}

InventoryCategory.modelName = "InventoryCategory";
```

So on action **CREATE_INVENTORY_ITEM_SUCCESS** I create the new Model record and every time I have to add InventoryItem id  inside InventoryCategory items list, same goes for deleting and re-fetching (throws if you try to insert id which already exists so you have to clear the ids first)

It would be great if one could simple create new record and the redux-orm to handle the rest. It should be possible since it has all the relations between Models (given the id being the linking attribute and supplied on create() ). Probably would have to do internally the same thing I am doing here.

Let me know what you think!

**Comment by markerikson** [comment]
You might want to try two things differently:  handling your updates in terms of the event instead of the individual model types, and using the `Model.upsert()` method instead of `Model.create()`.

I'm actually working on a new post for my ["Practical Redux" tutorial series](http://blog.isquaredsoftware.com/series/practical-redux/) that will cover some related aspects of handling models (as in, I'm literally writing the code now, I just saw this notification).

**Comment by rogic89** [comment]
I am doing the `upsert` instead of `create` when re-fetching but still have to check if the ID exists in related model  and add it if not for it to work, which I believe should not be necessary since orm has the all the data to handle it internally.

**Comment by haveyaseen** [comment]
This is the same as #215, just remove the `many()` field from `InventoryCategory` and specify `InventoryItem.fields` like this:
```javascript
static get fields() {
  return {
    id: attr(),
    category: fk('InventoryCategory', 'items'),
  };
}
```
