### ISSUE TITLE
All connected components re-render on any Model change

### ISSUE THREAD

**Issue by B-Reif** [tommikaikkonen/redux-orm#184]
I'm working on a survey authoring app. A Survey model has a list of Page models, and each Page has a list of Question models. Any change to any question model propagates a re-render to every Page, even if the changed question model is totally unrelated.

The issue arises from the Page's relation to questions. Each Page container selects the Page model's related questions:

```js
export const makePageQuestionsSelector = () => {
	return createSelector(orm, selectPresent, selectItemId, (session, id) => {
		const pageModel = session.Page.withId(id);
		const questions = pageModel.questions.toModelArray().map(q => q.id);
		return questions;
	});
};
```

My understanding of this is: by calling `toModelArray` on a question QuerySet, this selector clears its memoization after any change to any question. I'm only interested in a list of related Question ids, but any Question change--even to unrelated models--defeats the selector's memoization.

The primer todos demo exhibits similar mass re-rendering behavior. To observe:
- Use the React DevTools extension
- Visit http://tommikaikkonen.github.io/redux-orm-primer/
- Open the developer tools and enable "Highlight Updates"
- Interact with the Todos app. You should see highlights on every component in the app as everything re-renders after any change to any todo.

Should I be writing these selectors differently? How can I prevent these kinds of app-wide re-renders?

**Comment by markerikson** [comment]
I actually just asked a question over in #71 about your specific use case :)

**Comment by B-Reif** [comment]
Oh, nice :) We can close this then if you like.
