### ISSUE TITLE
Reverse ids are not being created

### ISSUE THREAD

**Issue by CharlesBradshaw** [tommikaikkonen/redux-orm#191]
Maybe this isn't expected but I find that when I call upsert on a model with a relation to another model, the related model is not updated to include the reverse id

For example if I had the models below
```
class A extends Model{}
A.modelName = 'A';
A.fields = {id: attr(),B: many('B')}

class B extends Model{}
B.modelName = 'B'
B.fields = {id:attr(),A: fk('A')}

```

and then If I upserted on A like so
`A.upsert({B:[1,2,3],id:1})`
None of B's foreign key would be updated, even if the B rows already exists

Is there a way to automatically add reverse relations ids? Does it happen by default but I did something wrong?

**Comment by CharlesBradshaw** [comment]
Assuming it's not implemented, if I wanted to create a pull request can someone give me an idea of the best way to go about it?

**Comment by haveyaseen** [comment]
@CharlesBradshaw Thanks for opening this issue. From what I understand the tests actually include this case, see [src/test/testIntegrations.js#L465](https://github.com/tommikaikkonen/redux-orm/blob/v0.10.0/src/test/testIntegrations.js#L465) for updates and [src/test/testIntegrations.js#L492](https://github.com/tommikaikkonen/redux-orm/blob/v0.10.0/src/test/testIntegrations.js#L492) for creates.

I think what you are missing is the `relatedName`, specified as a second argument to the `many` function, as in
```javascript
A.fields = {
  id: attr(),
  B: many('B', 'aModels'),
};
```
Compare to (in the [tests](https://github.com/tommikaikkonen/redux-orm/blob/v0.10.0/src/test/testIntegrations.js#L421))
```javascript
Team = class extends Model {};
Team.modelName = 'Team';
Team.fields = {
  id: attr(),
  name: attr(),
  users: many('User', 'teams'),
};
```
Also, unlike your `B` class the [`User` class](https://github.com/tommikaikkonen/redux-orm/blob/v0.10.0/src/test/testIntegrations.js#L414) does not contain a `fk` field:
```javascript
User = class extends Model {};
User.modelName = 'User';
User.fields = {
  id: attr(),
  name: attr(),
};
```
And maybe it would work better to pass the relatedName to `fk` instead and drop the `many` field (see #35):
```javascript
B.fields = {
  id: attr(),
  A: fk('B', 'bModels'),
};
```
If that still doesn't work for you, all I can say is that you should look into [`fields`](https://github.com/tommikaikkonen/redux-orm/blob/v0.10.0/src/fields.js) and [`descriptors`](https://github.com/tommikaikkonen/redux-orm/blob/v0.10.0/src/descriptors.js).

**Comment by CharlesBradshaw** [comment]
I copied the models from the test and got a many to many relationship to work, but I still can't get a many to one to work. When I searched through the tests I didn't see a one to many test that I could copy.

The first code snippet is the many to many relationship that works, the following code snippet is the changes I tried to make it a one to many relationship

Many To Many
```
import { Model, fk, many,attr} from 'redux-orm';
import { ORM, createSelector} from 'redux-orm';


export const User = class extends Model {};
User.modelName = 'User';
User.fields = {
    id: attr(),
    name: attr(),
};

export const Team = class extends Model {};
Team.modelName = 'Team';
Team.fields = {
    id: attr(),
    name: attr(),
    users: many('User', 'teams'),
};




const orm = new ORM();
orm.register(User,Team);

const ReverseRelationSelector = createSelector(orm, [state => state], (session) => {
  const TeamUsers = session.Team.all().toModelArray().map(Team => Team.users.toRefArray().map(x => x.id))
  const UserTeams =  session.User.all().toModelArray().map(User => User.teams.toRefArray().map(x => x.id))
  return [TeamUsers, UserTeams]
})


const sess = orm.session(undefined);
sess.User.upsert({id:1})
sess.User.upsert({id:2})
sess.User.upsert({id:3})

sess.Team.upsert({users:[1,2,3], id:1})

console.log(ReverseRelationSelector(sess.state))
/*
  [
    [[1,2,3]],
    [[1],[1],[1]],
  ]
*/
```

Many To One Snippet

I tried changing the User.fields to be a fk, but that seems to break all relations 

```
export const User = class extends Model {};
User.modelName = 'User';
User.fields = {
    id: attr(),
    name: attr(),
    team: fk('Team','users')
};

export const Team = class extends Model {};
Team.modelName = 'Team';
Team.fields = {
    id: attr(),
    name: attr(),
};

```
import { Model, fk, many,attr} from 'redux-orm';
import { ORM, createSelector} from 'redux-orm';


export const User = class extends Model {};
User.modelName = 'User';
User.fields = {
    id: attr(),
    name: attr(),
    team: fk('Team','users')
};

export const Team = class extends Model {};
Team.modelName = 'Team';
Team.fields = {
    id: attr(),
    name: attr(),
};




const orm = new ORM();
orm.register(User,Team);

const ReverseRelationSelector = createSelector(orm, [state => state], (session) => {
  const TeamUsers = session.Team.all().toModelArray().map(Team => Team.users.toRefArray().map(x => x.id))
  const UserTeams =  session.User.all().toModelArray().map(User => User.team)
  return [TeamUsers, UserTeams]
})


const sess = orm.session(undefined);
sess.User.upsert({id:1})
sess.User.upsert({id:2})
sess.User.upsert({id:3})

sess.Team.upsert({users:[1,2,3], id:1})

console.log(ReverseRelationSelector(sess.state))
/*
  [
    [[]],
    [[undefined],[undefined],[undefined]],
  ]
*/
```

if instead I put a fk on Users and a many on Team, the Team can access Users but Users can't access team

```
import { Model, fk, many,attr} from 'redux-orm';
import { ORM, createSelector} from 'redux-orm';


export const User = class extends Model {};
User.modelName = 'User';
User.fields = {
    id: attr(),
    name: attr(),
    team: fk('Team')
};

export const Team = class extends Model {};
Team.modelName = 'Team';
Team.fields = {
    id: attr(),
    name: attr(),
    users: many('User')
};




const orm = new ORM();
orm.register(User,Team);

const ReverseRelationSelector = createSelector(orm, [state => state], (session) => {
  const TeamUsers = session.Team.all().toModelArray().map(Team => Team.users.toRefArray().map(x => x.id))
  const UserTeams = session.User.all().toModelArray().map(User => User.team)
  return [TeamUsers, UserTeams]
})


const sess = orm.session(undefined);
sess.User.upsert({id:1})
sess.User.upsert({id:2})
sess.User.upsert({id:3})

sess.Team.upsert({users:[1,2,3], id:1})

console.log(sess.state)
console.log(ReverseRelationSelector(sess.state))
/*
  [
    [[1,2,3]],
    [[undefined],[undefined],[undefined]],
  ]
*/
```

**Comment by markerikson** [comment]
Looking back at the original issue description: I _think_ the described behavior is "correct" as designed.  The problem seems to be a misunderstanding of how the `many()` and `fk()` descriptors behave.

The point of a "foreign key" is that an instance of A exists, and some instance of B _knows_ that the A exists and has the A instance's id itself.  That is a distinct and different thing than a "many" relation.  Going off the top of my head, a `many()` descriptor creates a "through model" that maps between instances of A and instances of B, and it definitely will _not_ update an `fk()` field in a B instance.

**Comment by plandem** [comment]
you are trying to use it wrong. 'many-to-one' in your definition is a 'one-to-one' actually

**Comment by plandem** [comment]
I have another questions - what are you trying to achieve?

**Comment by CharlesBradshaw** [comment]
I can get you an actual json example but simply put, I make network requests that come back with a many to one relation that might look like so 
```
A : {
    id: 1,
    B: [1,2,3],
    //...other A properties
}
```
and I found that when I simply upsert A to include those B, when I would run a selector on the B, they had no reference to A. The solution I'm currently using is normalizr merge strategies to create the reverse relations that output data like the following snippet, and then loop over every A and B and update them. I didn't spend time writing the merge strategies well because I felt like anything fancy I did would be reinventing the wheel. 
```
A : [{
    id: 1
    B: [1,2,3],
    //...other A properties
}]
B: [
    { id: 1, A: 1},
    { id: 2, A: 1},
    { id: 3, A: 1},
]
```

**Comment by haveyaseen** [comment]
@CharlesBradshaw Yes, this seems to be exactly the thing you should do if your API looks like this. Fetch the `A` model and create the `B` models with the `idAttribute` of `A` in the `fk` field of `B`. Don't however pass the `B` field to the `A` records, this will then be managed automatically by Redux-ORM.
