### ISSUE TITLE
Uncaught TypeError: Class constructor Account cannot be invoked without 'new'

### ISSUE THREAD

**Issue by Aerendir** [tommikaikkonen/redux-orm#195]
This is the error:

> Session.js:69 Uncaught TypeError: Class constructor Account cannot be invoked without 'new'
>     at new SessionBoundModel (Session.js:69)
>     at Function.create (Model.js:339)
>     at bootstrapSuppliers (Page.jsx:18)
>     at Object../assets/components/Business/Suppliers/Page.jsx (Page.jsx:30)
>     at __webpack_require__ (bootstrap d43ea89017c2333de1bb:19)
>     at Object../assets/App.jsx (bootstrap d43ea89017c2333de1bb:62)
>     at __webpack_require__ (bootstrap d43ea89017c2333de1bb:19)
>     at ./assets/App.jsx.Object.defineProperty.value (bootstrap d43ea89017c2333de1bb:62)
>     at bootstrap d43ea89017c2333de1bb:62

I'm trying to populate the state with dummy data just to test how all the things work.

I'm following the outdated [Redux-orm Primer](https://github.com/tommikaikkonen/redux-orm-primer), updating methods calls according to the documentation found in this main repo.

This is the code I'm using:

```javascript
// Create an initial set of suppliers to test the state
function bootstrapSuppliers(orm) {
  const state = orm.getEmptyState();
  const session = orm.mutableSession(state);

  console.log(state, session);

  const { Account, Channel, Supplier } = session;

  Account.create({
    name: 'Test Account',
  });

  Channel.create({
    name: 'Test Channel',
  });

  Supplier.create({
    name: 'Test Supplier',
  });
}
bootstrapSuppliers(orm);
```

They have no relation at the moment: I want to just observe the redux state.

This is the model I'm using:

```javascript
import { Model, attr } from 'redux-orm';

class Account extends Model {
  static get fields() {
    return {
      id: attr(),
      name: attr(),
    };
  }
}
Account.modelName = 'Account';

export default Account;
```

Am I doing something wrong or there is a bug in the code?

**Comment by Chris-Congenica** [comment]
If might be worth looking at:
https://github.com/tommikaikkonen/redux-orm/issues/194
https://github.com/tommikaikkonen/redux-orm/issues/53

The issue seems to stem from the redux-orm code being transpiled and that not running correctly within test environments.

**Comment by Aerendir** [comment]
@Chris-Congenica , thank you for linking! I'm going to comment there! Hoping we will solve our issues -.-'

**Comment by Aerendir** [comment]
Ok, @Chris-Congenica , thanks to issues linked by you, I solved adding this to my `webpack.config.js` file as suggested by @markerikson here https://github.com/tommikaikkonen/redux-orm/issues/53#issuecomment-319761183:

```javascript
config.resolve.alias = { 'redux-orm': 'redux-orm/src' };
```
