### ISSUE TITLE
Importing the store in a simple function throws TypeError: Cannot read property 'session' of undefined

### ISSUE THREAD

**Issue by Aerendir** [tommikaikkonen/redux-orm#198]
I'm using Redux-orm with React and Redux without problems.

Now I'm implementing JWT authentication.

I have a function `fetch()` that I use to call the API endpoints.

Now that I have the JWT authentication in place, this function `fetch()` has to use a `token` to get authorized to call the API.

This `token` is stored in the `state`.

Instead of passing the `token` from thunks, I'd like to get it directly from the `state` and directly in the `fetch()` function.

So I'm doing something like this:

```javascript
// utils/fetch.jsx

// See below to see how "store" is created
import store from 'config/store';

export default function(url, options = {}) {
  ...
  console.log(store.getState());
  ...
}
```

But this throws:

> redux.js:26 Uncaught TypeError: Cannot read property 'session' of undefined
    at redux.js:26
    at redux.js:355
    at Array.forEach (<anonymous>)
    at assertReducerShape (redux.js:353)
    at combineReducers (redux.js:409)
    at Object../assets/reducers/index.jsx (index.jsx:7)
    at __webpack_require__ (bootstrap c70de97af272dd20923a:19)
    at Object../assets/config/store.jsx (store.jsx:5)
    at __webpack_require__ (bootstrap c70de97af272dd20923a:19)
    at Object../assets/utils/fetch.js (fetch.js:3)

I'm creating the store this way:

```javascript
// config/store.jsx

import { createStore, applyMiddleware } from 'redux';
import { composeWithDevTools } from 'redux-devtools-extension/developmentOnly';
...
// See below to see how "rootReducer" is created
import rootReducer from 'reducers/';

function configureStore(preloadedState) {
  ...
  const store = createStore(rootReducer, preloadedState, composedEnhancer);

  return store;
}

const store = configureStore();

export default store;
```

Then I have my `rootReducer` composed this way:

```javascript
// reducers/index.jsx - rootReducer

import { combineReducers } from 'redux';
// See below to see how "orm" is created
import orm from './orm';
...

const rootReducer = combineReducers({
  orm,
  ...
});

export default rootReducer;
```

`orm` reducer is created this way:

```javascript
// reducers/orm

import { createReducer } from 'redux-orm';
// See below to see how "ormConfig" is created
import ormConfig from 'config/orm';

const orm = createReducer(ormConfig);

export default orm;
```

And finally this is `ormConfig`:

```javascript
// config/orm

import { ORM } from 'redux-orm';
import Model1 from 'models/Model1';
import Model2 from 'models/Model2';
... // Other models

function configureOrm() {
  const orm = new ORM();
  orm.register(Model1, Model2 /* , Model3, Model4, ecc. */);

  return orm;
}

const orm = configureOrm();

export default orm;
```

My App entry point is a classic entry point:

```javascript
// App.jsx

ReactDOM.render(
  <Provider store={store}>
    <React.StrictMode>
      <Coommercio />
    </React.StrictMode>
  </Provider>,
  document.getElementById('Coommercio')
);
```

If I import the `store` only in `App` all works fantastically well.

But if I try to import the `store` also in `fetch.jsx` I receive the error above.

If I remove the `orm` reducer from the composed reducers, all works well again (but without the `orm` slice, obviously!).

Any ideas to help me use the `store` both in `React` components and in the `fetch` function?

**Comment by Aerendir** [comment]
The problem seems not related to `redux-orm` but to Webpack importing instead as trying `console.log(ormConfig)` actually returns `undefined`.

It seems the file is not imported at all...

**Comment by vdhand-xactly** [comment]
@Aerendir I am facing the same error, how did you resolve it? Although, I am not using webpack. I am using Vite
![image](https://user-images.githubusercontent.com/84094035/122570140-77f16280-d019-11eb-9826-17b3323e417c.png)

**Comment by Aerendir** [comment]
I solved continuing to pass the token from the thunk to the `fetch()` function.

Like this:

```javascript
import fetch from 'App/Utilities/fetch';

export function showThunk(IntId) {
  return (dispatch, getState) => {
    dispatch(showLoadingAction(IntId, true));

    const token = ctxGetUserToken(getState());
    const placeholders = [{ replace: '____', value: IntId }];

    fetch(SHOW_ENDPOINT, token, placeholders)
      .then((response) => response.json())
      .then((data) => {
        dispatch(showSuccessAction(data));
        dispatch(showLoadingAction(IntId, false));
      })
      .catch((e) => {
        dispatch(showErrorAction(IntId, e.message));
        dispatch(showLoadingAction(IntId, false));
      });
  };
}
```
