### ISSUE TITLE
need example how to use batch mutations.

### ISSUE THREAD

**Issue by plandem** [tommikaikkonen/redux-orm#20]

**Comment by tommikaikkonen** [comment]
They are built in internally, there is no public API, so you're already using it :) All the updates you make in a session will be applied as a batch when you call `getNextState`. Previously each update in a session, whether deletion, creation or attribute update, created copies of the objects. Now, if an object was copied or created earlier on in the session, it is mutated directly.

**Comment by plandem** [comment]
i see. thanks. maybe it's better to update docs, for me it was not clear.
