### ISSUE TITLE
npm start throws error

### ISSUE THREAD

**Issue by dash042** [tommikaikkonen/redux-orm#21]
Hi Tommi,

this may be a noob problem, but I can't get your code to run.
"npm install" tells me fsevents is not compatible for me (arch linux) - but this seems to be optional?
"npm start"  inside the cloned repository directory gives me an error (Error: Path must be string - received undefined.) and therefore I can't check the app locally in my browser.
could you please give me a little hint?

Thank you sincerely!
Daniel

**Comment by markerikson** [comment]
Well, this is a library, not an actual application.  Looking at the package.json in this repo, there's no "start" NPM run script defined, just "test" and "prepublish".  And yes, fsevents is an optional sub-dependency for Babel or ESLint or something like that.

Beyond that, you may want to actually look through the readme in the front page of this repo, as well as the sample project / tutorial at https://github.com/tommikaikkonen/redux-orm-primer .
