### ISSUE TITLE
Is the second argument to fk and many necessary?

### ISSUE THREAD

**Issue by ernsheong** [tommikaikkonen/redux-orm#214]
Some parts of the README provide a second argument to `fk` and `many`, some don't. So is it necessary?

**Comment by haveyaseen** [comment]
No, it is not necessary. To be precise, [the constructor of `RelationalField`](https://github.com/tommikaikkonen/redux-orm/blob/dd89014a2ef451867823b0b106a1bd0e820adaa5/src/fields.js#L181) allows you to pass either a single object or one/two strings:
```javascript
if (args.length === 1 && typeof args[0] === 'object') {
    const opts = args[0];
    this.toModelName = opts.to;
    this.relatedName = opts.relatedName;
    this.through = opts.through;
    this.throughFields = opts.throughFields;
} else {
    [this.toModelName, this.relatedName] = args;
}
```
If the first argument is an object and that object does not contain a `relatedName` field, this will be determined automatically ([`reverseFieldName`](https://github.com/tommikaikkonen/redux-orm/blob/dd89014a2ef451867823b0b106a1bd0e820adaa5/src/utils.js#L67)):
```javascript
function reverseFieldName(modelName) {
    return modelName.toLowerCase() + 'Set'; // eslint-disable-line prefer-template
}
```
So if you specify an `author: fk('Author')` field on a Book model, then for any instance `author` of `Author` you will need to access their list of books by writing `author.bookSet`.

The same goes for the `through` field on many-to-many fields if you don't pass an object with the `through` key specified ([`m2mName`](https://github.com/tommikaikkonen/redux-orm/blob/dd89014a2ef451867823b0b106a1bd0e820adaa5/src/utils.js#L35)):
```javascript
function m2mName(declarationModelName, fieldName) {
    return declarationModelName + capitalize(fieldName);
}
```
If you have a Book model with a `genres: many('Genre')` field, then the through model will be called `BookGenres`.

**Comment by ernsheong** [comment]
Thank you for the thorough explanation 👍. I feel this warrants a bit more explanation in the README, or at least in the non-existent Wiki :)

**Comment by haveyaseen** [comment]
@ernsheong This is also explained in our JSDoc documentation: https://tommikaikkonen.github.io/redux-orm/global.html#many :slightly_smiling_face:
