### ISSUE TITLE
Understanding Many constraint 

### ISSUE THREAD

**Issue by franferns** [tommikaikkonen/redux-orm#223]
while creating an Author/Books example. I am trying to add a list of Authors and its associated books . Below is the code to for Author/Book.

![image](https://user-images.githubusercontent.com/779253/42693326-749e8b1a-86cc-11e8-8726-fa9c010c6be1.png)

I then for testing purpose use the debug console and manually add values.
1. _To the Author table_ 
![image](https://user-images.githubusercontent.com/779253/42693479-e91a3354-86cc-11e8-8455-f3c168df7227.png)
2. _To the books from many relation _
![image](https://user-images.githubusercontent.com/779253/42693644-658d877e-86cd-11e8-8973-456e8b696871.png)

When i add to the books from Author.withId("0").books.add({}) shouldnt there be an entry created for it too in the Books table so when i do a Book.all().count() the count is of all books ?

![image](https://user-images.githubusercontent.com/779253/42693760-cba625e8-86cd-11e8-8278-0575c3a03127.png)

Please help me understand this.

**Comment by haveyaseen** [comment]
You must create the `Book` model instances yourself, and `add` will only cause the relationship between Author and Book to be registered. `toBookId` in the `AuthorBooks` instance should just be the id of a book.

```javascript
// assuming the following:
Book.idAttribute == 'ISBN' // true
const book = Book.create({ISBN: '93293293HGHG', title: 'APP Insights'});
session.Author.withId("0").books.add(book);
// or
session.Author.withId("0").books.add(book.ISBN);
```
