### ISSUE TITLE
[Question] How to handle initial state

### ISSUE THREAD

**Issue by piu130** [tommikaikkonen/redux-orm#228]
Lets say I have this model:

```js
class Book extends Model {
    static reducer(action, Book, session) {
        switch (action.type) {
        case 'CREATE_BOOK':
            Book.create(action.payload);
            break;
        // Return value is ignored.
        return undefined;
    }
}
```

and I want the initial book: `Introduction to Redux-ORM`.

In redux I could return the initial state, but in redux-orm return value is just ignored.

Is there an easy way to set the initial state (create some initial books)?

**Comment by haveyaseen** [comment]
Hi @piu130. The easiest way is to use a mutable session to make your state. See the following example from our test helpers.

https://github.com/tommikaikkonen/redux-orm/blob/abe87236b4c2755afd8946b70cb199c5aece50b5/src/test/helpers.js#L232-L249

So the minimal steps are:

1. `const state = orm.getEmptyState();`
2. `const { Book } = orm.mutableSession(state);`
3. `Book.create({ name: 'Clean Code' });`
4. `state` has now been mutated by `Book.create` as we created a mutable session. Start a regular immutable session using `orm.session(state);`.

You could also pass `state` by yourself. Its format must be as follows:

https://github.com/tommikaikkonen/redux-orm/blob/abe87236b4c2755afd8946b70cb199c5aece50b5/src/test/unit/Database.js#L93-L111

**Comment by piu130** [comment]
Thanks but I don't know where to place this code :)
I have the file `orm.js`:
```js
import { ORM } from 'redux-orm'
import Book from './Book'

const orm = new ORM()
orm.register(Book)

export default orm
```
and in `index.js` I have:
```js
import { createReducer } from 'redux-orm'
import orm from './orm'

export default createReducer(orm)
```
And this I pass to the `createStore` function.

**Comment by haveyaseen** [comment]
It entirely depends on how you retrieve the initial state, if you can hardcode it or similar.
I guess you could do it similar to the way that @Aryk did it (https://github.com/tommikaikkonen/redux-orm/issues/69#issuecomment-268504665):

```javascript
import { defaultUpdater } from 'redux-orm/lib/redux';

const initializeState = (orm) => {
    const state = orm.getEmptyState();
    const { Book } = orm.mutableSession(state);
    Book.create({ name: 'Clean Code' });
    return state;
};

const createReducer = (orm, updater = defaultUpdater) => {
    return (state, action) => {
        const session = orm.session(state || initializeState(orm));
        updater(session, action);

        return session.state;
    };
};
```

**Comment by piu130** [comment]
Would be nice to have an easier way, like passing initialState as a third argument :) But it worked this way. Thanks.

**Comment by haveyaseen** [comment]
Glad that I could be of help. And I agree, there should be an easier way to pass initial state. Even asynchronously, considering that users might want to leverage Redux actions. Putting this on our v1 roadmap.
