### ISSUE TITLE
Setting resource and retrieve it

### ISSUE THREAD

**Issue by blaadje** [tommikaikkonen/redux-orm#229]
Hello,
I didnt see anything talking about that so i dunno if it makes sense. I'll explain the issue :
I got 2 resources : `Movie` and `Category` 
So 1 `Category` has many `Movies` and a `Movie` belongs to a `Category`.

My `Movie` has a reducer like that : 
```js
export default class Movie extends Model<MovieItems> {
  static reducer (action: any, Movie: any): ORMState | undefined {
    switch (action.type) {
      case API_FETCH_SUCCESS:
        action.payload.map((item: MovieItems) => {
          // here i'd like to do something similar to that 
          Movie.create(item).category.set(item.categoryId)
        })
        break
    }
```
so i could access the movies like that `session.Category.first().movies.toRefArray()`
and it would give me array of `Movies`

If you guys have any idea how to do something like that with keeping the reducer into the Movie model

**Comment by haveyaseen** [comment]
Hi @blaadje, this shouldn't be necessary. With our newest release ([v0.12.1](https://github.com/tommikaikkonen/redux-orm/releases/tag/v0.12.1)) all you need is the following:
```javascript
class Movie extends Model<MovieItems> {
  static reducer (action: any, Movie: any): ORMState | undefined {
    switch (action.type) {
      case API_FETCH_SUCCESS:
        action.payload.map(Movie.create)
        break
}

Movie.fields = {
    id: attr(),
    categoryId: fk({
        to: 'Category',
        as: 'category',
        relatedName: 'movies',
    }),
}

export default Movie
```

**Comment by blaadje** [comment]
Ok thank you perfecto :1st_place_medal: :smile:
