### ISSUE TITLE
Model.update broken for many-to-many relations

### ISSUE THREAD

**Issue by markerikson** [tommikaikkonen/redux-orm#23]
`Model.update()` checks to see if a given field to update is a many-to-many relation.  If so, it tries to use a function called `arrayDiffActions()` to determine which IDs have been added or removed from the existing list.  It's trying to import that function from utils.js, but the function no longer exists.  Looks like it was removed in commit 560c81df9dca1d1c2ee6e273b218bd9f31ec7700 on May 9, while working on adding use of the immutable ops lib.  

As a result, `Model.update()` currently breaks due to the undefined function reference.

**Comment by tommikaikkonen** [comment]
Sorry for the delay here -- was on a trip for a couple of weeks.

Looks like I didn't have a test in place to catch that regression. Wrote test to catch regression and fixed it in https://github.com/tommikaikkonen/redux-orm/commit/72daf370884fa0ab023ee3f40dcf40b97d7f8efa, will make a new release later today.

**Comment by markerikson** [comment]
Sure.  In the meantime, I wrote a utility function for myself that does fairly similar behavior.

**Comment by carlesnunez** [comment]
Can u give me more info about that?

I am trying to update a model with a many relationship and im getting with that error:
Possible Unhandled Promise Rejection (id: 0):
Tried to add already existing XXX id(s)

**Comment by carlesnunez** [comment]
Self response:

If we go to the file Model.js we can see in the line 425

`if (idsToAdd.length > 0 && currentIds.length > 0) {`

That is causing a bug on the update of an empty many relationship array. Is not deleting any relationship but instead is adding links to relationships. That is causing a problem on the update process throwing the error that I pasted before
