### ISSUE TITLE
Selector returns empty array (react native)

### ISSUE THREAD

**Issue by karelnet** [tommikaikkonen/redux-orm#230]
Hi,

I'm struggling to retreive data with a selector in my react native app.
I'm using redux ORM 0.12.1

Here is my bootstrap :

```
// reducers/intentions.js
import {
  ORM, Model, fk, attr,
} from 'redux-orm';

export class Intention extends Model {
  static reducer(action, MyIntention) {
    switch (action.type) {
      ... 
    }
  }
}
Intention.modelName = 'Intention';
Intention.fields = {
  id: attr(),
  title: attr(),
 ....
};

export const orm = new ORM();
orm.register(Intention);

export default orm;
```
My selector : 

```
/selectors/intentions.js
import { createSelector } from 'redux-orm';
import { orm } from '../reducers/intentions';


const todayIntentions = createSelector(
  orm,
  state => state.orm,
  (session) => {
    console.log('Running intention selector');
    return session.Intention.all().toRefArray(); // Should show all intentions for the moment
  },
);

export default todayIntentions;
```

and finally, my React Native component where I would like to retreive data (see console.log in it) : 

```
import React, { Component } from 'react';
import {
  FlatList, Animated, View, StyleSheet,
} from 'react-native';

import { connect } from 'react-redux';
import Globals from '../Globals';
import todayIntentions from '../../redux/selectors/intentions';


class MyComponent extends Component {
  constructor(props) {
    super(props);

    console.log('Today intentions in props:', this.props.todayIntentions); // ---> SHOWS AN EMPTY ARRAY
    console.log('Full data from store :', this.props.intentions); // ---> shows raw data from store
  }

  render() {
    return (
      <View style={styles.mainView}>
....
      </View>
    );
  }
}

const styles = StyleSheet.create({
  mainView: {
    flex: 1,
    backgroundColor: Globals.COLOR.BACKGROUND,
  },
});


// This function takes the Redux state, runs the
// selectors and returns the props passed to App.
function mapStateToProps(state) {
  return {
    intentions: state.intentions,
    todayIntentions: todayIntentions(state),
  };
}

export default connect(mapStateToProps)(MyComponent);

```

Important precision : data is loaded from redux-persist when app starts (with many Intentions in it)

Why do I have an empty Array from the selector ? I expect to have all intentions as an array I can use to show data.

Thanks

**Comment by haveyaseen** [comment]
The only thing that seems strange to me about your code is that you're retrieving `intentions` as a direct child of `state`. In a Redux-ORM setup `intentions` would be a bit deeper in the hierarchy and should only be read via selectors. Please post your reducer setup (root reducer) and how exactly you are persisting and loading your state.

In theory it should be possible to persist the current state of a Redux-ORM session (`persistedState = someSerializer(someSession.state)`) and later load it back into the Redux tree using `orm.session(someDeserializer(persistedState))` but it seems to me you are doing that all of this outside of Redux-ORM. However I haven't worked with redux-persist so I don't know how it would come into play with Redux-ORM or if the two libraries can function together at all.

**Comment by haveyaseen** [comment]
Sure :slightly_smiling_face: Well, that clears things up a bit. Your selector `todayIntentions` does not do what it's supposed to because your `ORM` instance is actually stored in `state.intentions` (if state is your Redux store object). So the second argument to `createSelector`, i.e. `state => state.orm`, does not really return your `ORM` instance but `null` instead. There currently is no `orm` key in your store.

I recommend changing your root reducer as follows:
```javascript
// if possible, move the creation of your ORM object and the registration of your models into a different file than intentions for clarity
import orm from './intentions';

const rootReducer = combineReducers({
  auth,
  orm: createReducer(orm),
});
```
And remove the `intentions` key from the object returned in `mapStateToProps`, you're actually just accessing the `ORM` instance there, which should not be exposed to React components.

**Comment by karelnet** [comment]
Thank you that was pretty simple, but I'd never thought about that on my own.
