### ISSUE TITLE
Show loading status when calling dispatch multiple times for Redux-ORM with around 300 reducers

### ISSUE THREAD

**Issue by franferns** [tommikaikkonen/redux-orm#233]
We use Redux-ORM which has around 300 reducers . I have a React Component where in we make around 4 calls to Web API and then to insert that data into the Redux-ORM . The dispatch gets called immediately where has the reducers take sometime to complete. 

I added a reducer for loading with an action type of "START_LOADING" and "END_LOADING" . which returns true for START_LOADING and false for END_LOADING. 

when i call dispatch for startLoading with the calls to web api in between startLoading() and endLoading(). They get called even before the reducers are executed. 

How do i get the correct loading status until all the reducers get completely executed ?

![image](https://user-images.githubusercontent.com/779253/46933598-54a8d500-d072-11e8-8fc8-ad247e96e619.png)

![image](https://user-images.githubusercontent.com/779253/46933644-8883fa80-d072-11e8-8861-77995b40a884.png)

![image](https://user-images.githubusercontent.com/779253/46933733-ec0e2800-d072-11e8-8070-99bd2bf849d5.png)

![image](https://user-images.githubusercontent.com/779253/46933666-a2254200-d072-11e8-8e97-f311be268b45.png)

Thanks

**Comment by haveyaseen** [comment]
Try to make the reducer return `state` instead of `false` in the `default` case. Otherwise it will get reset to `false` immediately whenever _any_ action other than `START_LOADING` occurs.
