### ISSUE TITLE
How to integrate redux-orm with a REST API data source

### ISSUE THREAD

**Issue by Abdull** [tommikaikkonen/redux-orm#236]
How can redux-orm be used on the client side to manage entities accessible from a server-side REST API?

Let's say I have a REST API with endpoints `api/authors` and `api/books`.

An author can have many books, and a book can have many authors.

A GET to `api/authors/1` would return the following payload:

```
{
  "id": 1,
  "name": "Some Author",
  "booksIds": [30, 31]
}
````

A GET to `api/books/30` would return the following payload:

```
{
  "id": 30,
  "title": "Some book title",
  "authorsIds": [1, 2]
}
````

A GET to `api/books/31` would return the following payload:

```
{
  "id": 31,
  "title": "Another book title",
  "authorsIds": [1]
}
````

As you can see, the REST API does not return "fat" JSON payloads but only IDs to related entities.

I'd like my redux-orm application to lazily retrieve data from the REST API so that I can navigate along the entity relationships without worrying whether some entity is already "cached" in the redux-orm store.
So for example, having user 1 already "cached" in my redux-orm store, calling `user1.getBooks().map(book => book.title)` would return an array `['Some book title', 'Another book title']`.

I'm currently stuck applying redux-orm to my React frontend as its store does not automatically fill the Redux store with entity data (existing at the REST endpoint) which hasn't been loaded into the client redux store yet.

**Comment by haveyaseen** [comment]
Hey @Abdull :slightly_smiling_face:  It is not apparent to me what is not working in your code. Identifiers will be stored in the through model for many-2-many relationships even when referenced model instances do not exist, yet.

Please post your `User` and `Book` models (or whatever they're called in your ORM) including their field definitions. Also tell us what exactly is going wrong. As long as you are just using `Book.create` and `Book.update` -- and not `Book.authorsIds.remove(someId)` for instance -- there shouldn't be any issues. See e.g. https://codesandbox.io/s/oj3qz8k5xz.

**Comment by Abdull** [comment]
Hi @haveyaseen, thank you for your [Codebox](https://codesandbox.io/s/oj3qz8k5xz?expanddevtools=1). It's a great scenario to elaborate on what I would like to achieve leveraging redux-orm:

In your `index.js` at line 29, the redux-orm state has data for a book entity which has the following authors: `AuthorID: [123]`.

As redux-orm's state does not have an author entity with id `123` at this point yet, the following statement
```
console.log(
  "First book's authors:",
  session.Book.first().AuthorID.toRefArray()
);
```
will log `First book's authors: []`. From redux-orm's perspective, this makes sense.

But what I would like to achieve is: whenever data for an entity is missing (in this case, an author with id `123`), *something* will fetch that data from where it can be found (e.g. from a REST endpoint).

This would be nice to have because then we can have client-side React components which e.g. list all authors' names for a book even though some of these authors may not be in the client-side redux-orm store. Data would be fetched on demand from the server-side REST endpoint.

**Comment by haveyaseen** [comment]
Thank you for this food of thought. As a library we have absolutely no control over the backend and the logic of communicating with backends (message delivery semantics, timeouts, synchronization etc). From that perspective it's clearly out of scope, and for good reason.

Some people do these kinds of things with the meta field in Redux-ORM but I don't think it's elegant to couple these ideas (low cohesion). Instead I would recommend to have some Higher-Order Component handle this logic. Thanks to the flexibility of Redux itself you can re-use the actions you define for your models' reducers in other (non-ORM) reducers and action creators.
