### ISSUE TITLE
How to use redux-orm in real world app

### ISSUE THREAD

**Issue by Zarwlar** [tommikaikkonen/redux-orm#242]
Hi. I'd like to ask you about using redux-orm in real-world app. In particular how do you avoid a lot of boilerplate code when you use it? And how do you organizing your state with data which doesn't hold in orm-state? In other words, do you split your state on normalized state and other state which could holds location, ui,  side-effects data etc?

**Comment by markerikson** [comment]
Check out my ["Practical Redux" tutorial series](https://blog.isquaredsoftware.com/series/practical-redux) for examples of how to use Redux-ORM.

**Comment by Zarwlar** [comment]
Thanks!
