### ISSUE TITLE
`withId` not working.

### ISSUE THREAD

**Issue by relaxomatic** [tommikaikkonen/redux-orm#244]
I'm having an issue with the `withId` model function. 
I have just started using this so I may have misinterpreted something.
```
const getById = createSelector(
  orm,
  state => state.orm,
  (session, id) => {
    const user = session.User.withId(id + '');
    return user ? user.ref : null;
  }
);

const getWhere = createSelector(
  orm,
  state => state.orm,
  (session, constraints) => {
    const user = session.User.filter(constraints).first();
    return user ? user.ref : null;
  },
);

const getAll = createSelector(
  orm,
  state => state.orm,
  (session) => session.User.all().toRefArray(),
);

describe('Select user', () => {
  it('User id configured correctly!', () => {
    expect(ormData.User.idAttribute).toEqual('id');
  });
  it('Select all works!', () => {
    const users = getAll({ orm: ormData.state });
    expect(users.length).toEqual(3);
    expect(users[0].id).toEqual('1');
  });
  it('Select user 1 generally works!', () => {
    const user = getWhere({ orm: ormData.state }, { id: '1' });
    expect(user).not.toBeNull();
    expect(user.id).toEqual('1');
  });
  it('Select user 1 withId works!', () => {
    // Getting
    const user = getById({ orm: ormData.state }, '1');
    expect(user).not.toBeNull();
    expect(user.id).toEqual('1');
  });
});
```

Everything works until the last part, using the reducer that uses `withId`. 

Anyway is the a bug, or am I doing something wrong? Perhaps it has something to do with the id's being integer strings?

**Comment by relaxomatic** [comment]
Just as some extra info, if I use integers instead for the id's I search with, the outcome is still the same.

**Comment by relaxomatic** [comment]
Ok ignore this, the id just isn't getting through :/

**Comment by relaxomatic** [comment]
For anybody making the same mistake, this is to create a selector much like reselect where it is a based on combining selectors to make arguments for the final selector. So does not except arguments.

However what you can do is have the selector return a function(instead of just the selected state), that you can filter the result set on.

e.g. 
```
const getById = createSelector(
  orm,
  state => state.orm,
  orm => 
    id => {
      const user = orm.User.withId(id);
      return user ? user.ref : null;
    }  
);
```
so if I called the function `getById ` it would return a function with the resulting `orm` state in scope.
In my case I can use it as
```
const getByIdFilter = getById(state);//Get a filter with access to orm
const user = getByIdFilter(1);//Execute the filter with a passed argument
```

Added to this we can also memoize that function, so that the function doesn't re-execute if the argument is the same. i.e....
```
const getById = createSelector(
  orm,
  state => state.orm,
  orm => memoize(
    id => {
      const user = orm.User.withId(id);
      return user ? user.ref : null;
    }
  )
);
```

**Comment by relaxomatic** [comment]
Further reading here
`https://github.com/reduxjs/reselect/blob/master/README.md#q-how-do-i-create-a-selector-that-takes-an-argument`

**Comment by haveyaseen** [comment]
@relaxomatic Selectors are now composable and accept ID arguments with automatic caching based on re-reselect! Please try out [v0.14.0-rc.0](https://github.com/redux-orm/redux-orm/releases/tag/v0.14.0-rc.0) :slightly_smiling_face:
