### ISSUE TITLE
Cannot read property 'items' of undefined

### ISSUE THREAD

**Issue by Elijen** [tommikaikkonen/redux-orm#31]
I am trying to query state in `mapStateToProps` like this:
```
function mapStateToProps(state) {
  let session = schema.from(state);
  session.Tab.map(tab => {
    console.log(tab.widgets.toModelArray());
  });

  return {}
}
```

But I am getting the following error:
![screen shot 2016-08-14 at 10 06 06 pm](https://cloud.githubusercontent.com/assets/1304054/17651634/9ff1f522-626b-11e6-8b6c-6ddb70c56100.png)

Model definitions are simple:
```
Tab.modelName = 'Tab';

Widget.modelName = 'Widget';
Widget.fields = {
  tab: fk('Tab', 'widgets')
}
```

Am I doing something wrong?

**Comment by markerikson** [comment]
How are you hooking up Redux-ORM with your state?  Do you actually need to be initializing the session with a sub-piece of the state, such as `const session = schema.from(state.entities);` ?

**Comment by Elijen** [comment]
@markerikson Yep, that was the problem. Thanks :)

**Comment by Elijen** [comment]
@tommikaikkonen Thanks, I am planning to use selectors later. For now I am usually just getting a single object by its id in `mapStateToProps` so I don't think the benefit would be very big (correct me if I am wrong).

**Comment by frederic-bonjour** [comment]
Hi,

First of all: **thank you for this great library!**

I'm using redux-orm server-side, and I'm facing the same issue:

```
TypeError: Cannot read property 'items' of undefined
    at Table.accessList (/Users/user/Dev/luciol-bridge/node_modules/redux-orm/lib/db/Table.js:130:22)
    at Table.query (/Users/user/Dev/luciol-bridge/node_modules/redux-orm/lib/db/Table.js:198:17)
    ...
```
This occurs in the reducer:
```
const session = orm.session(dbState);
const {Group, Device} = session;

switch (action.type) {
    case SET_GROUP_DEVICES:
        Group.withId(action.id).set('devices', action.deviceIds);
        break;
}
```

I also tried with:
```
Group.withId(action.id).set('devices', action.deviceIds.map(id => Device.withId(id)));
```
or:
```
Group.withId(action.id).devices.add(25); // arbitrary ID for the example :)
```

Initial state is built like this (from JSON files on disk):
```
const lastStateValueByKey = {
    Device: null,
    Group: null
};


function getInitialState() {
    const state = {};
    for (const key in lastStateValueByKey) {
        if (lastStateValueByKey.hasOwnProperty(key)) {
            try {
                state[key] = JSON.parse(FS.readFileSync(Path.join(__dirname, '..', 'data', `${key}.json`), {encoding: 'utf8'}));
            } catch (e) {
                state[key] = {items:[], itemsById: {}, meta: {maxId: 1}};
            }
        }
    }
    return state;
}

let initialState = getInitialState();
console.log(initialState);

let store = createStore(
    ormReducer,
    initialState,
    applyMiddleware(thunk)
);
```
The files _Device.json_ and _Group.json_ exist and are correctly loaded when I `console.log()` the initial state:
![capture d ecran 2018-05-04 a 18 28 16](https://user-images.githubusercontent.com/2297602/39639237-f6f0d356-4fc8-11e8-8f94-57f77c6f3623.png)


**Saving entities without relations works fine, though ;)**

Any idea?
