### ISSUE TITLE
Does this work with React Native?

### ISSUE THREAD

**Issue by kevando** [tommikaikkonen/redux-orm#33]
I assume so, but I'm kind of new to react/redux and curious if anyone has thoughts or feedback or problems they've run into?

**Comment by markerikson** [comment]
Should work just fine - it's pure Javascript, and in fact, the React Native site even has this article: http://www.reactnative.com/getting-started-with-react-native-and-redux/ .

**Comment by kevando** [comment]
Thanks @markerikson 

I have a rn app with redux and I want to include this orm because my data is becoming very relational. 

I've yet to see an example though, so I am trying to build his [example](https://github.com/kevando/redux-orm-example) app in react native right now. Hoping it goes well :)

**Comment by kevando** [comment]
I am currently getting an [error like this](https://github.com/reactjs/react-redux/issues/339) so I am not sure if this depends on babel? I'm also not sure if react native uses babel.. hmm.

**Comment by tommikaikkonen** [comment]
I see no reason why the library wouldn't work in React Native. As to your error, Redux-ORM is transpiled with Babel, but it's not a package dependency when you use it as a library. When you require the `redux-orm` package in JS, you're pulling code that has already been transpiled to ES5.
