### ISSUE TITLE
Defining further relationship information fields on redux-orm 'through' models

### ISSUE THREAD

**Issue by greatwillow** [tommikaikkonen/redux-orm#34]
Given in the Redux-orm docs, the following information about an internal 'through' model class is specified:

"Redux-ORM internally mimics relational databases and creates a new "table" for many-to-many relations, represented by an internal "through" Model class. So when we define this field on a Todo:

tags: many('Tag', 'todos'),
Redux-ORM creates a model named TodoTags, that's entities are in this form:

{
    id: 0,
    fromTodoId: 0,
    toTagId: 1,
}"

Is it possible to access this 'through' model class in order to add extra fields that further define the relationship that exists between the two entities.  For example, if two classes such as a 'Customer' class and a 'Product_Purchased' class were related here, could I define relationship properties on this relational 'through' class such as the quantity purchased or the date of the customers purchase.  

ie.
{
   id: 0,
   fromCustomerId: 10
   toProduct_PurchasedId: 340,
   quantityPurchased: 12,
   purchaseDate: 04-02-2016,
}

For further clarification with regards to what I am referring to, a very clear explanation can be found under the 'Extra fields on many-to-many relationships' subtitle in the django 'models' documentation at https://docs.djangoproject.com/en/1.10/topics/db/models/  .  Any input would be appreciated.  Thanks!

**Comment by tommikaikkonen** [comment]
I've worked extensively with Django so I know where you're coming from.

Through models are on the todo-list. You can access the generated model through the session, but you can't create your own through model yet. The workaround currently would be to either

1. Create a model to act as the through model with foreign keys to both sides of the relationships, and add any additional information you want to maintain, and manually manage the through relationship. A lot more verbose than using real through-models, but fully supported with the current feature set.
2. Use the automatically generated through model, but manually edit the underlying representation after ending the session to provide the data you need. This is very hacky, and would be horribly wrong for all but the most simplest cases.

I'll see if I can find time to implement through models and some additional deletion strategies in the next few weeks!

**Comment by greatwillow** [comment]
Great!  Thanks for your response here!  It looks like the first solution here may be the most straight-forward at the moment, though am glad to hear you may be able to implement this feature in the future!

**Comment by tommikaikkonen** [comment]
Update on this... Implementation of this is in #39, basic syntax is

```js
// in Author model
articles: many({
  to: 'Article',
  through: 'Authorship',
  relatedName: 'authors',
  // optional, but required if you have more than one foreign key
  // to either of the models, you need to specify these fields.
  throughFields: ['article', 'author'],
})
```

Here `Authorship` is a model with `article` and `author` foreign keys.

Just needs documentation and more testing. I'll try to get those done this week.
