### ISSUE TITLE
Mutation of static `backend` prop on Model

### ISSUE THREAD

**Issue by diffcunha** [tommikaikkonen/redux-orm#37]
I found that if we set `backend` on a Model and then start a session with `schema.withMutations(...)` (for bootstrap for instance) this will change the static `backend` prop setting `withMutations` to `true`. From this point on every time we make a change we are literally mutating the store. 

The bug is in `Model.js` file

```js
// Model.js
static getBackend() {
    if (!this._sessionData.backend) {
        const BackendClass = this.getBackendClass();
        const opts = this._getBackendOpts();

        if (this.session && this.session.withMutations) {
            // HERE! This will mutate the static prop `backend` on the Model
            opts.withMutations = true; 
        }

        // ...
    }
    return this._sessionData.backend;
}
```

**Comment by tommikaikkonen** [comment]
Fixed in release `0.8.3`
