### ISSUE TITLE
Relation logic assumes integer IDs

### ISSUE THREAD

**Issue by markerikson** [tommikaikkonen/redux-orm#4]
Per [descriptors.js line 102](https://github.com/tommikaikkonen/redux-orm/blob/9fd72f2148c8e713f121b07c82a8f6ea8175adb6/src/descriptors.js#L102), the relations logic assumes that an ID will be an integer.  I'm using string IDs, so this check fails, and then the `entity.getId()` call throws an exception because that obviously doesn't exist.

I tried modifying descriptors.js to do `if (Number.isInteger(entity) || typeof entity === "string")`, and that appeared to allow the creation logic to run successfully.  Probably a better way to handle it, but this seemed to work for me.

**Comment by tommikaikkonen** [comment]
Thanks for opening the issue @markerikson . Hotfixed this straight to master, published on NPM as `0.1.22`. Now the logic in descriptors doesn't assume any specific type of id argument - it checks if it has a `getId` property of type `function`, and if so calls it to get the id value.
