### ISSUE TITLE
Selectors taking a single model ID as an argument

### ISSUE THREAD

**Issue by jasonslam** [tommikaikkonen/redux-orm#40]
If it is not recommended to use Models in the view layer and instead add getters as attributes on the plain objects, then how do I create selectors that operate on single models only? I have already implemented selectors that transform related data and return an object with IDs as keys and the selected data as values. Please consider something like this:

```javascript
Todo.all().ref // [{id: 123, user: 456}]

// Container component:
function mapStateToProps(state) {
        return {
                todoStatus: todoStatus(state), // some intense computation also using other models' data
        };
}

// in Container component
this.props.todoStatus // {123: "finished"}

// in selectors file - similar to this
const todos = createSelector(
        state => state.orm,
        schemaObj.createSelector(session => (
            session.Todo.all().toRefArray()
        ))
);

const todoStatusRelatedData = createSelector(
        state => state.orm,
        schemaObj.createSelector(session =>
            session.TodoStatusRelatedData.all().toRefArray()
        )
);

export const todoStatus = createSelector(
        [todos, todoStatusRelatedData],
        (todos, todoStatusRelatedData) => {
            const statuses = {};
            for (let todo of todos) {
                statuses[todo.id] = ... // some computation using todoStatusRelatedData
            }
            return statuses;
        }
);

// in one component that renders another component which needs a todo's status:
<TodoStatusComponent status={todoStatus[todo.id]} />
```
How do I turn this into a selector that gets me the status for a particular todo only, so that I can pass functions to components that are lower in the hierarchy to select only based on the todo that is currently being dealt with?
In the end I want to go from `todoStatus[todo.id]` to `todoStatus(todo.id)` (some wrapper function that is created in the container component's `mapStateToProps` containing a reference to the state or the session) to prevent computing all statuses when only some are going to be needed. Also, this code is really ugly, having all those for loops just to map IDs to related data.

**Comment by markerikson** [comment]
What do you mean by "not recommended to use Models in the view layer" ?  That's one of the main points of Redux-ORM - it has all that relational lookup logic already implemented.  All you should need to do is:

```js
function mapState(state) {
    const todoStatus= {};

    const session = schema.from(state.orm);
    const {Todo} = session;
    Todo.all().forEach(todo => todoStatuses[todo.id] = todo.status);

    return {todoStatus};
}
```

**Comment by jasonslam** [comment]
Yes, that is technically possible and similar to what I am doing now. What I meant by view layer is directly using Models in React.Component.render() instead of patching getters onto POJO references.

This issue is about calling selectors while rendering so as to make sure selectors only get executed for the models that are actually being rendered. Something similar to this:

```
class TodoDetail extends React.Component {
    render() { // CURRENT
        const { todo, todoStatuses } = this.props;
        return <TodoStatus status={todoStatuses[todo.id]} />;
    }
    render() { // DESIRED
        const { todo, todoStatus } = this.props;
        return <TodoStatus status={todoStatus(todo.id)} />;
    }
}
```

If I put the `status` calculating code inside the Todo model then I have no way of correctly memoizing the output and I would have to be using `this.getClass().session[modelName]` to get other models which is why I believe a selector is the correct solution for this.

However I have not got any good version to completely work yet so this may as well be premature optimization.

**Comment by markerikson** [comment]
Yeah, I would definitely not worry about optimizations yet.  I'm a firm believer in "Make it work, make it right, make it fast" - first build something that works even if it's ugly, then figure out a better/cleaner structure for it, _then_ profile and see where any bottlenecks are.

Personally, I would completely avoid referencing Redux-ORM models in my React components, same as I would want to avoid referencing Immutable.js types in my components if I were using that library.  I'm also not sure why your example shows use of a selector function inside of `render()`.  You would want to use selectors inside of your `mapState` function, so that you can encapsulate state shape and avoid unnecessary re-renders.

**Comment by jasonslam** [comment]
I understand, thanks a lot. Even if this means I have to include that weird boilerplate syntax (always creating kind of a Map in each selector). There probably is some way to refactor that as well.
