### ISSUE TITLE
UMD build / Class constructors cannot be invoked without 'new'

### ISSUE THREAD

**Issue by a-laughlin** [tommikaikkonen/redux-orm#41]
Appreciate the `redux-orm` concept.  Tried testing it out with Redux and React served in a local html file for simplicity, and `<script src="node_modules/redux-orm/lib/index.js">` leaves chrome choking on `exports`.  Any chance you can configure Webpack to also output as UMD when publishing?  A UMD build would also be really handy to share examples in jsbin/jsfiddle/codepen/etc.

**Comment by a-laughlin** [comment]
Attempting to use redux-orm in node without webpack.  Tried installing and configuring webpack to export a UMD build.  Hit [this error](https://github.com/tommikaikkonen/redux-orm/issues/29).  Not sure I got the configs right.  FWIW, generating a UMD build using correct webpack/babel configs could reduce the need to troubleshoot others' transpiling issues.

**Comment by a-laughlin** [comment]
In node6/electron, I repeatedly got the error "Class constructors cannot be invoked without 'new'" when using `<ModelName>.create({})`.  Turns out that the current babel config doesn't work for all environments, so a UMD build still breaks.  Figured out a correct config.  Small additions to package.json. Will submit a PR for reference.

**Comment by tommikaikkonen** [comment]
UMD build is added in `0.8.4`.
