### ISSUE TITLE
Any confirmations of redux-orm working in node/electron?

### ISSUE THREAD

**Issue by a-laughlin** [tommikaikkonen/redux-orm#43]
Redux-orm works great in the browser.  In electron, something as simple as:

```
// in a reducer w/ args (state, action, sessionizedBook, session)
const book1 = sessionizedBook.create({name:'foo'});
book1.authors.add('john doe');
```

fails at https://github.com/tommikaikkonen/redux-orm/blob/62b479340e716fcb3fe70bd570685a2d53933ce9/src/Model.js#L354
with stack:

```
Backend.js:63 Uncaught TypeError: Cannot read property 'items' of undefined(…)
accessIdList @ Backend.js:63
accessIds @ Model.js:279
nextId @ Model.js:334
```

Anyone know what might be going on, or has anyone else gotten redux-orm working in node/electron?  I'm thinking it's likely some sort of babel config, and some configuration of the presets' plugins fail in node in subtle ways.  Maybe all the use of "this" with arrow functions being native in node now?  Suggestions appreciated.

Using babel config in #42.  The original babel config failed with invalidateClassCache #29.

**Comment by a-laughlin** [comment]
Hmm.  Getting the same error with the 8.4 UMD build.  I'm also evaluating architecture changes which may make it a non-issue.  At the very least it'll make the problem easier to track down.  I'll post back if I learn anything.

**Comment by pronebird** [comment]
I have it working with Electron out of box..

**Comment by a-laughlin** [comment]
Glad you got it working! Thanks for the comment!  Going to close this out.  I didn't fully figure out what the issue was, but it seemed to be that something in my code was changing the context, breaking some of redux-orm's many internal "this" references.
