### ISSUE TITLE
Sync with a backend database

### ISSUE THREAD

**Issue by martinwells** [tommikaikkonen/redux-orm#44]
Wondering what is the best practice for syncing the local redux-orm db with a backend API? Do you just add in custom API request/actions in the model?

**Comment by tommikaikkonen** [comment]
Yes, incoming data from a backend is just another action that transforms the state. You can abstract that logic somewhere depending on what you need. E.g. you could make a `hydrate` static method on the model that takes an arbitrary number of model props for a single model (an array of objects), applies any deserialization logic on each and then calls `Model.create` with those objects. Then in the reducer, you'd handle a backend API action by passing the array of objects to `Model.hydrate`.

Personally I haven't had to deal with complex backend API sync, so other people might have better ideas how to structure that logic.

**Comment by markerikson** [comment]
That's actually almost exactly what I do in my own app!  I called it `parse` instead of `hydrate`, but yeah, that's what I'm using to load in my data instead of Normalizr.

I also added a `toJSON()` method to my models as well, since the backend API is still expecting the data in nested form.

**Comment by markerikson** [comment]
As a side note, I'm actually hoping to write a blog post within the next 2-3 weeks about my own usage of Redux-ORM, and some of the techniques I've come up with while using it.  That technique is one of the ones I plan to mention.

My blog's at http://blog.isquaredsoftware.com , if you want to check in on it later.  (Also, I did just publish a post on  [Idiomatic Redux: Why Use Action Creators?](http://blog.isquaredsoftware.com/2016/10/idiomatic-redux-why-use-action-creators/) that might be of interest as well) .

**Comment by ferronrsmith** [comment]
can you provide an example of how you would synchronize the redux-orm with the backend ?

**Comment by markerikson** [comment]
My own app has a bunch of JSON-RPC CRUD APIs for each of my main data types, so my general approach tends to be something like:

```js
export function saveSomeItemType(itemID) {
    return (dispatch, getState) => {
        const session = createSession(getState());
        const {SomeType} = session;
        
        const item = SomeType.withId(itemID);
        // Call custom serialization function I wrote, which returns plain JS
        // data for this item and any of its relations
        const data = item.toJSON();
        
        serverAPI.someType.update(data)
            .then((updatedDataFromServer) => {
                dispatch({
                    type : "UPDATED_ITEM",
                    payload : {
                        itemID,
                        itemAttributes : updatedDataFromServer,
                    },
                });
            });
    }
}
```

**Comment by ferronrsmith** [comment]
@markerikson thanks for this.

**Comment by NE-SmallTown** [comment]
@markerikson Hi,mark,could you give me a summary why you don't use normalizr?AFAIK,normalizr can do nomalize and deNormalize well

**Comment by markerikson** [comment]
A couple reasons.  First, I started using Redux-ORM right after it was released, and it fits my use case well.  Second, at the time, Normalizr did not have a denormalization capability built-in (there was a separate "denormalizr" lib out there).

**Comment by NE-SmallTown** [comment]
Yea,get it,thanks
