### ISSUE TITLE
Nested relationships?

### ISSUE THREAD

**Issue by developer239** [tommikaikkonen/redux-orm#47]
Hi,
how do I handle nested relationships? Let's say that I have:

Sports -> has many leagues
Leagues -> has many Tournaments
Tournaments

I want to access tournaments in sports. How do I do that?

**Comment by developer239** [comment]
I got it! Kind of. Is this the best practice? :) It would be really cool if you added more examples. This library looks really powerful.

```
export const sports = createSelector(
  ormSelector,
  state => state,
  schema.createSelector((orm, state) => {

    // Query sports
    return orm.Sport.map(sport => {

      // Get sport ref
      const obj = sport.ref

      return Object.assign({}, obj, {
        // Query leagues
        leagues: sport.leagues.map((league) => {

          // Get league ref
          const objLeague = league.ref

          // If is defined (i think I got error when I did not check for undefined variables)
          if (league === undefined) {
            return {}
          } else {
            return Object.assign({}, objLeague, {
              // Query tournaments
              tournaments: league.tournaments.withRefs.map((tournament) => {
                // Return tournament name
                return tournament.name
              })
            })
          }
        })
      })
    })
  })
)
```

**Comment by markerikson** [comment]
I think you're making this too complicated.  The lookups are what Redux-ORM is supposed to handle for you.

Here's a rough sketch of what you probably need (not tested, but hopefully will show you the idea):

```js
import {Model, many} from "redux-orm";
class Tournament extends Model {}

class League extends Model {
    static get fields() {
        return {
            tournaments: many("Tournament"),
        };
    }
}

class Sport extends Model {
    static get fields() {
        return {
            leagues: many("League"),
        };
    }
}

// usage example:
const sport = Sport.withId(sportId);
sport.leagues.tournaments.withModels.forEach(tournament => console.log(tournament.name));
```

**Comment by developer239** [comment]
Thank you for your answer I really appreciate it. I am afraid that what I am trying to do is not that simple.

I have these tables:

- Sports
    - has many leagues
- Leagues
    - has many Tournaments
- Tournaments
    - has many series

It is basically a tree. I want to build a table. I am used to working with MySQL. If it was a MySQL I would simply:
- `SELECT sports.*, leagues.*, tournaments.*, series.* FROM sports [LEFT JOIN leagues, tournaments]`

The number of rows selected would multiply with each LEFT JOIN. This is important. I want the result of the selector as similar to hypothetical MySQL result as possible. Also it would be cool to be able to filter the results. Is there any simple way how to achieve that?

**Comment by developer239** [comment]
I thought that redux-orm selectors have same roles as repositories in Doctrine? :)
