### ISSUE TITLE
Error setting a value on a 1:1 model instance

### ISSUE THREAD

**Issue by markerikson** [tommikaikkonen/redux-orm#5]
I've got a several types (Route, RouteLeg, etc) that have a 1:1 mapping to a CheckState model.  I'm trying to do a series of parsing/processing steps while loading data from the server.  I first initialize all my models from the loaded data, after which I need to calculate the values for these CheckState objects based on the related data.

During this process, I'm calling a function on a model instance to update itself, which tries to assign an updated value to a property on the CheckState instance attached to it.  This crashes down in `Backend.update()` when it tries to call `idArr.reduce()`, but idArr is undefined.

I see that `payload.idArr` is defined in `forwardManyToOneDescriptor()` and `Model.update()`.  However, my use case appears to be hitting the property setter defined in `Model._initFields()`, and THAT code path does not appear to be defining an "idArr" field on the payload.

Here's the current relevant definition of my model class:

```js
class RouteLeg extends Model {
  static backend() {
    return {
      idAttribute : "legID"
    }
  }

  static get fields() {
    return {
      start : oneToOne("Node"),
      subpoints : many("Node"),
      checkState : oneToOne("CheckState")
    }
  }

  updateCheckState() {
    let childNodes = [this.start].concat(this.subpoints.objects());
    let nodeCheckStates = childNodes.map(nodeModel => nodeModel.checked);
    let newCheckState = determineCheckStateFromChildren(nodeCheckStates);

    // Crashes here
    this.checkState.value = newCheckState;
  }
}
```

**Comment by markerikson** [comment]
Followup: just playing around with the library, adding "idArr" and "updater" to the payload defined in Model.js appeared to make things work properly:

```js
set: (value) => {
    ModelClass.addUpdate({
        type: UPDATE,
        payload: {
            [idAttribute]: this.getId(),
            idArr : [this.getId()],
            updater : {
                [fieldName]: value
            }
        },
    });
},
```

**Comment by tommikaikkonen** [comment]
Thanks for opening the issue! You got it right, the problem was in [`Model._initFields`](https://github.com/tommikaikkonen/redux-orm/blob/54ed9ec285e8c730f26b6533f62efa88c7ab38b3/src/Model.js#L57). Looks like it regressed after I changed the internal update action format from two update actions (update a single instance, update many instances) to a single one (update many instances).
