### ISSUE TITLE
Not really immutable

### ISSUE THREAD

**Issue by developer239** [tommikaikkonen/redux-orm#51]
Is there any way how to keep references after ordering / filtering selected values? I have a really long list of items. Every item is getting rerendered unless I stop the rendering in shouldComponentUpdate lifecycle method.

```
export const ormSelector = state => state.orm

export const allTodos= schema.createSelector(ormSelector, session => {
  return session.Todo.withRefs.all()
})

export const filterTodos= createSelector(
  [ allTodos],
  (items) => {

    console.log(_.isEqual(items.all(), items)) // true
    console.log(items.all() === items) // false
    console.log(_.isEqual(items.filter(() => true), items)) // false
    console.log((items.filter(() => true)=== items)) // false
    console.log(_.isEqual(items.filter(() => true).withRefs, items)) // true
    console.log((items.filter(() => true).withRefs === items)) // false

})
```

What am I missing?

**EDIT:**
Fast forward few months into the future. I think that I was not using react / redux as I was supposed to. I converted Immutable structures to JS BEFORE i passed them as props to my components. I am not really sure about this but I am quite confident that that was causing all my problems.

Comparisons showed above are totally pointless.

**Comment by markerikson** [comment]
Redux-ORM's API returns QuerySet instances for pretty much all of the collection-type functionality.  Those instances contain IDs for the items they match, and a couple flags relating to whether lookups should return the actual item references or Model instances.  A new QuerySet instance is returned for each call like `all()` or `filter()`, so no, they won't ever be referentially equal.

You should not try to return a QuerySet instance from selectors or `mapState` functions.  You would generally want to do things like returning an array of item IDs, the actual item object references, or data extracted from the refs/models.  My view is that components shouldn't actually know anything about Redux-ORM at all.

**Comment by developer239** [comment]
I actualyl used redux-orm the way you describe but when I started filtering the list of my items and when I decided to create composed selectors I realized that I actually don't know what am I doing.

So to select all todos:

export const ormSelector = state => state.orm
export const allTodos = schema.createSelector(ormSelector, session => {
  return session.Sport.all().toRefArray() // query all -> return array of references
})

export const filterTodos= createSelector(
  [ allTodos],
  (items) => {
    return items.filter(()=>true) // return all items filtered
})

In component:

```
function mapStateToProps (state) {
  return {
    filteredItems: filterTodos(state),
  }
}
```

asdf

**Comment by developer239** [comment]
Also is there any advantage using `schema.createSelector` over `createSelector`?

**Comment by tommikaikkonen** [comment]
You should use `schema.createSelector` as that will not recompute if an unrelated Model state changes. Using `reselect.createSelector` will cause a recompute whenever anything the Redux-ORM state changes.

Looking at the `allTodos` selector, it should only recompute if the `Todo` model state has been updated, and should return a reference to the same array otherwise. Maybe something unexpected is updating the Todo model state?

For debugging selector issues, I first recommend reading [the algorithm explanation here](https://github.com/tommikaikkonen/redux-orm/blob/master/src/memoize.js#L11). It's pretty straightforward and will help you understand both the flexibility and limitations of Redux-ORM selectors.

**Comment by Aryk** [comment]
@markerikson - On that topic, was wondering:

1. According to the docs:

> When you want to iterate through all entities with filter, exclude, forEach, map, or get an item with first, last or at, you don't always need access to the full Model instance - a reference to the plain JavaScript object in the database could do.

If there are associations on that model how can we easily get the fully nested object as plain JS? Do we have to loop through manually or create functions on top? 

2. If we do have deep nested objects and we want to do comparisons on them, would it make sense to introduce a library like ImmutableJS to handle the "shallow" equalities so that we can make our Components pure? I'm thinking this would be returned at the mapState level. So, building on #1 above, we would traverse the model using redux-orm methods, convert it to the raw JS, and then fromJS it to make it immutable, and have the schema.selector memoize that?

**Comment by markerikson** [comment]
Yeah, in my own app I've added `toJSON()` methods on my models, which know what relations that model has, and recurse through them.  Rough example:

```js
class SomeModel extends Model {
	toJSON() {
		const data = {
			...this.ref,
			singleRelation : this.singleRelation.toJSON(),
			manyRelation : this.manyRelation.map(item => item.toJSON()),
		};
		
		return data;
	}
}
```

I primarily use that approach when I need to serialize the entire object, whether it be sending it to the server, or copying an item and its relations from my "current items" slice to the "editing/draft/WIP" slice.

I would ***definitely not*** try to use Immutable.js's `fromJS()` method in conjunction with this.  Per Lee Byron, `fromJS()` and `toJS()` are the most expensive methods in Immutable.js, and should only be used in rare situations.  (See the [React Performance#Immutable Data](https://github.com/markerikson/react-redux-links/blob/master/react-performance.md#immutable-data) section of my links list for references.)

I personally don't use Immutable.js, for a variety of reasons.  Related, I don't think that Redux-ORM and Immutable.js would get along well, and given how Redux-ORM works and what capabilities it offers, I think it offers enough safety and benefits in data handling that Immutable.js isn't needed anyway.

In my own app, my `mapState` functions are still pretty naive performance-wise.  I haven't yet spent time trying to implement any real optimizations, other than a memoized selector that ensures there's only one Session instance per store update.  I'm holding off until after I'm basically feature-complete to do benchmarking and perf optimization.

**Comment by Aryk** [comment]
Got it, that makes a lot of sense. I figured that those methods were probably expensive. ;)

The toJSON seems like a good solution. Thanks for the tips and advice!

**Comment by markerikson** [comment]
Sure.

FYI, if you haven't seen it yet, my ["Practical Redux" blog series](http://blog.isquaredsoftware.com/series/practical-redux) starts off with a couple articles on [Redux-ORM Basics](http://blog.isquaredsoftware.com/2016/10/practical-redux-part-1-redux-orm-basics/) and [Redux-ORM Concepts and Techniques](http://blog.isquaredsoftware.com/2016/10/practical-redux-part-2-redux-orm-concepts-and-techniques/), and Part 5 (which I'm literally in the middle of writing right now) will show an example of using models to load data into the store.  Should have that published mid-week.

**Comment by Aryk** [comment]
Wow, looks great, looking forward to seeing the final version.
