### ISSUE TITLE
Reset orm state

### ISSUE THREAD

**Issue by valerybugakov** [tommikaikkonen/redux-orm#52]
What is the right way to reset state of the ORM? For example on logout action.
Btw thanks for an awesome library!

**Comment by markerikson** [comment]
Two main ways:

1) Use `schema.getDefaultState()` to get an "empty set of tables" object, and return that from a reducer
2) Create a session based on the existing data, and for each data type that needs to be cleared, run something like `session.SomeType.all().forEach(item => item.delete())`

**Comment by valerybugakov** [comment]
Is there any difference between?
`session.SomeType.all().forEach(item => item.delete())`
`session.SomeType.all()..delete()`

The main problem of this method is that there's no way to delete all the data at once, right? It should be a separate reducer for each Model and they should execute in the right order (first models with foreign key fields) because if not, redux-orm will throw an error about undefined model reference on the next `session.SomeType.all().delete()`

**Comment by kennykaye** [comment]
Another solution, though somewhat inelegant may be to globally handle your `LOGOUT` action.

`createReducer` takes as its [second parameter](https://github.com/tommikaikkonen/redux-orm/blob/master/src/redux.js#L16) an `updater` function, which in turn calls each modelClass's `reducer`.

You could override with something like the following:

```javascript
function modelUpdater(session, action) {
  session.sessionBoundModels.forEach(modelClass => {
    if (typeof modelClass.reducer === 'function') {
      if (action.type === LOGOUT) {
        modelClass.all().toModelArray().forEach(item => item.delete())
      } else {
        modelClass.reducer(action, modelClass, session)
      }
    }
  })
}

// ...

createReducer(orm, modelUpdater)
```

**Comment by plandem** [comment]
You need to create own ORM reducer and return a new empty state when **reset** action is requested...something like this:
```js

export function defaultUpdater(session, action) {
    session.sessionBoundModels.forEach((modelClass) => {
        if (typeof modelClass.reducer === 'function') {
            // This calls this.applyUpdate to update this.state
            modelClass.reducer(action, modelClass, session);
        }
    });
}

export const createReducer = (orm, updater = defaultUpdater) =>
    (state, action) => {
        const ormState = (action.type === 'RESET') 
                ? orm.getEmptyState() 
                : state || orm.getEmptyState();

        const session = orm.session(ormState);
        updater(session, action);
        return session.state;
    };
```
