### ISSUE TITLE
Working with models from React

### ISSUE THREAD

**Issue by pronebird** [tommikaikkonen/redux-orm#56]
Just trying to wrap my head around redux-orm.

Is there any way to safely work with models directly from React (without mutating them)? 

Default example showcases the use of `.ref` which makes a plain object copy of Model. But since my model provides useful methods, I can't use them if I get plain objects back to React.

**Comment by markerikson** [comment]
You might want to read the two articles I just wrote on using Redux-ORM.  See Part 1 and Part 2, starting here: http://blog.isquaredsoftware.com/2016/10/practical-redux-part-1-redux-orm-basics/ .

**Comment by pronebird** [comment]
Thanks, closing for now.
