### ISSUE TITLE
Virtual fields

### ISSUE THREAD

**Issue by pronebird** [tommikaikkonen/redux-orm#58]
Is it possible to have computed fields that participate in the output of ref object but never saved to state?

What I currently do is:

```js
export const selectAll = schema.createSelector(session => {
  return session.Foo.map(item => {
    const obj = item.ref;
    const raw = Object.assign({}, obj);

    raw.foo = item.foo();
    raw.bar = item.bar();

    return raw;
  });
});
```

But it sucks because I have to do that in each piece of code that returns items.

**Comment by tommikaikkonen** [comment]
I think keeping `item.ref` as a simple reference to the plain object in the store is important; it keeps selectors fast.

If you're duplicating that logic in several selectors, you could implement a method on the Model to return an object that gets the values from methods you wish (e.g. `toJS`). A simple standalone function that takes a Model and returns it would work too.

**Comment by pronebird** [comment]
Yeah! Good thinking. With the help of redux-orm-proptypes I am able to add two functions to achieve that! Because `defaultProps` has the list of all fields with default values I can rely on that.

```js
class FooBar extends ValidatingModel {

  lean() {
    let virtual = {
      foo: this.foo(),
      bar: this.bar()
    };

    return Object.assign(virtual, this.ref);
  }
  
  prepare(lean) {
    const result = Object.assign({}, lean);
    const keysForUpdate = Object.keys(lean);
    const existingKeys = Object.keys(this.ref);

    for(const key of keysForUpdate) {
      if(!existingKeys.includes(key)) {
        delete result[key];
      }
    }

    return result;
  }
}
```

**Comment by pronebird** [comment]
Closing for now because there is a workaround and I think if we add fields declaration (#59) then we could do the same job as `prepare` in my case when updating data.
