### ISSUE TITLE
Can I pass an id to createSelector?

### ISSUE THREAD

**Issue by ghost** [tommikaikkonen/redux-orm#65]
My use case: I'm using redux-saga to process an action to get information from server. All I have in my action payload is the id of the object and I need to get other information from the object before I can call my server api. (I'm new to react/redux and still learning and haven't got quite got my head around all this.)

Is there a way to pass an id to createSelector to get an object from a list? In the primer, there is a selector to get all todos, but not one to get a single todo. The get single user selector in the primer uses information from the state. The id I want to use is not in state but needs to be passed in as a parameter.

Could someone show me how to write a selector to get a single todo from the todos list using (redux-orm) createSelector without getting the id of the todo from state?

**Comment by markerikson** [comment]
If you have a `Session` instance, you can do:

```js
const theModel = session.MyModelClass.withId(id);
```

Lemme point you towards a few resources.  First, I keep a big list of links to high-quality tutorials on React, Redux, and related topics, at https://github.com/markerikson/react-redux-links .  Specifically intended to be a great resource for anyone trying to learn the ecosystem.

Second, definitely read through the Redux-ORM docs.  The README in this repo is a good intro, there's the [Redux-ORM Primer](https://github.com/tommikaikkonen/redux-orm-primer) example, and then there's the [API docs](http://tommikaikkonen.github.io/redux-orm/index.html).

Finally, I recently wrote a couple blog posts discussing some ways to use Redux-ORM: [Redux-ORM Basics](http://blog.isquaredsoftware.com/2016/10/practical-redux-part-1-redux-orm-basics/) and [Redux-ORM Concepts and Techniques](http://blog.isquaredsoftware.com/2016/10/practical-redux-part-2-redux-orm-concepts-and-techniques/).

**Comment by Jafula** [comment]
@markerikson Your blog posts are what got me using redux-orm in the first place. I am watching your battlemechs with interest! I appreciate you blogging about redux-orm. I think it is neat,

http://tommikaikkonen.github.io/redux-orm/Schema.html

createSelector - args: zero or more input selectors and the selector function

The createSelector docs show an example  of how to use the function with just one argument, the selector function. I'm wondering what the syntax is to pass input selectors in and can one of those input selectors just be a plain javascript integer somehow?

**Comment by markerikson** [comment]
Ah, gotcha.  

I actually haven't used Redux-ORM's `createSelector` function yet myself.  Looking at the examples in the "Redux-ORM Primer" page, I'm pretty sure that they show exactly what you're looking for.  See this section: https://github.com/tommikaikkonen/redux-orm-primer#writing-selectors .  I suppose that instead of passing in a selector that retrieves a `selectedId` from the state, you could do something like `_.constant(42)`, which would create a function that always returns `42`, or something along that line.

Gotta say I'm glad to hear that A) someone is actually reading my "Practical Redux" series, and that B) it actually sounds useful! :)  I would actually be very interested in any feedback you have on the series - content, post formatting, topics, etc.  If you get a chance, I'd appreciate any thoughts or comments you have as comments on the posts themselves, or issues on the Project Mini-Mek repo!

**Comment by markerikson** [comment]
Just to follow up on this thought a bit: looking back at your original use case description, I do think the sort of "ad-hoc query" approach should be fine, ie, just `session.MyModelClass.withId(someId)`.  Looking up the data for a single item before making an AJAX call doesn't seem like something that needs to be hyper-optimized, and using `Session.createSelector()` looks like a performance optimization that would be mostly be useful for connected components that are looking up data.

**Comment by arminconscia** [comment]
Ya I'm having a similar issue of wanting to query a table after state updates with variables from component props, and there is little information on doing so. If someone has some best practices for this with Redux-ORM that would be super helpful

**Comment by markerikson** [comment]
@arminconscia : see the blog posts I linked in my earlier comment.  Also, note that #62 will drastically change things once it's done.

**Comment by arminconscia** [comment]
Did so, and thanks. Only question is when i run a query of:

session.DataModel.withId(id),

My return object looks like just has  _fields and _fieldnames keys (along with getters and setters for the model class) I can use the _fields but I am sure that I'm doing this incorrectly.

**Comment by markerikson** [comment]
That should be correct.  Redux-ORM looks at the plain JS object you have for that item in state, creates a Model instance that it will return, and adds properties on the Model instance for each of the fields in that object, as well as properties for each of the relational fields.

**Comment by arminconscia** [comment]
Alright cool, Thanks for your help Mark.
