### ISSUE TITLE
Handle paging

### ISSUE THREAD

**Issue by tarjei** [tommikaikkonen/redux-orm#7]
Hi, this seems to me to be a very nice library!

Two/three things struck me when looking at it:

1. You should support paging in selectors
2. How do you handle server side queries? 
For example, Let's say I've done two queries for users, one "name=n*" and one "name=r*" how can I switch between these two datasets?

Also, do you have a plan/roadmap for getting to 1.0?

**Comment by tommikaikkonen** [comment]
Hey tarjei,

Thanks! **First question.** Support for pagination is something that can be easily added. However, I'm leaning towards not implementing it in this package, but as an extension. There aren't any examples currently, but it's really easy to create extensions to Redux-ORM.  What kind of API would you suggest for pagination? Here's a simple implementation example.

In Redux-ORM, we have the `QuerySet` class that handles a set of entities. We can implement a `paginate` function as an instance method of `QuerySet`.

```javascript
import { Model, QuerySet, Schema } from 'redux-orm';
import chunk from 'lodash/array/chunk';

class PaginatingQuerySet extends QuerySet {
    paginate(pageSize) {
        const entities = this._withRefs
            ? this.toRefArray()
            : this.toModelArray();
        return chunk(entities, pageSize);
    }
}
// To be able to call the paginate method straight
// from the model, if you want.
PaginatingQuerySet.addSharedMethod('paginate');
```

Then you would assign the PaginatingQuerySet class to a Model class.

```javascript
class ModelWithCustomQuerySet extends Model {}
// The queryset class used to instantiate a queryset.
ModelWithCustomQuerySet.querySetClass = PaginatingQuerySet;
```

Then, presuming you're storing the current page number in your state, you could implement a selector like this.

```javascript
const paginationSelector = createSelector(
    state => state.orm, // select the redux-orm slice of the state
    state => state.selectedPageNumber,
    schema.createSelector((session, pageNo) => {
        const paginated = session.ModelWithCustomQuerySet
            .filter({ active: true }) // any arbitrary filtering you want to do...
            .withRefs
            .paginate(2);
        // The above would return
        // [
        //     [{ id: 0 }, { id: 1 }],
        //     [{ id: 2 }, { id: 3 }],
        //     [{ id: 4 }]
        // ]

        // Returns the selected page
        return paginated[pageNo]
    })
);
```

If you wanted to publish a package, you would add `redux-orm` to peer dependencies and add the PaginatingQuerySet class as the package's export. Then another developer can `import PaginatingQuerySet from 'redux-orm-paginate'` and use that in their app.

**Second question.** Just so we're on the same page: with Redux-ORM, you start ORM sessions by supplying a plain JS objects that looks like a relational database. Usually you don't have to deal with it yourself, but it looks like this:

```javascript
const database = {
    // "Table"
    User: {
        // "Row" id's
        items: [],
        // "Row" data by id, also acts as an index by id
        itemsById: {},
    },
    BlogPost: {
        items: [],
        itemsById: {},
    }
};
```

Then you start a session from that object:

```javascript
const session = schema.from(database);
session.BlogPost.withId(...)... // do queries and updates.
```

When you receive data from a server, I presume you'll want to merge the data to your database. You could make a new database object and add data to that, but I don't see the utility in keeping a separate database for that (unless you want to query those different datasets returned from the server totally separately).

You'll need to write the merge code yourself. Let's say you're receiving denormalized data from the server and you use `redux-thunk`.

1. In your action creator, you make an async request. Upon receiving the response, you take the data and normalize it using `normalizr`.
2. Still in the action creator, you dispatch an action `RECEIVE_USERS_AND_OTHER_STUFF` with the payload being the normalized data.
3. The data will be received in reducers. You could implement a User model like this to update the state based on the new data:

```javascript
import Model from 'redux-orm';
import forOwn from 'lodash/object/forOwn';

class UserWithApiHydrating extends Model {
    static receiveUsers(userPropsMap) {
        // userPropsMap is an object in the form
        // {
        //   0: {
        //     name: 'Tommi',
        //   },
        //   ...
        // }
        const newUsers = forOwn(userPropsMap, (userProps, userId) => {
            let user;
            try {
                user = this.withId(userId);
            } catch {
                user = this.create({ id: userId, ...userProps });
            }
        });
    }

    static reducer(state, action, UserWithApiHydrating) {
        const { type, payload } = action;
        switch (type) {
        case 'RECEIVE_USERS_AND_OTHER_STUFF':
            UserWithApiHydrating.receiveUsers(payload.users);
        }

        // Optional return, will be implicitly called if we return undefined.
        return UserWithApiHydrating.getNextState();
    }
}
```

**Third question.** I have some things I want to implement and improve before 1.0.

- Improve documentation
- Improve test coverage
- Make sure the API for building extensions is good. Meaning that it's easy to add custom functionality to Models, QuerySets, Backends, Fields, and make a reusable, publishable packages out of them that are easy for others to use. The current situation is pretty good, but I think the biggest improvement can be made with Fields - currently it's hard to implement custom Field functionality.
- The ability to specify custom Through models for many-to-many relations
- Add more flexible Field options. Currently they take a related model name and a reverse field name. For example, you could pass an options object to specify a custom Through model for a many-to-many fields.

**Comment by tarjei** [comment]
Hi Tommy!

Great answers, thanks!

Some more questions, the first is a nitpick :) :

1. In the example above you write:
```
            try {
                user = this.withId(userId);
            } catch {
                user = this.create({ id: userId, ...userProps });
            }
```

You do know that using try, catch as a nice if is very bad for performance, right?

2. Wrt to paging, what I'm trying to get at here is handling paging and filtering that is happening **on** the server and how that should be reflected in the local model so that you can get that back from the database. 

3. Have you used this with Immutable.js? 

Kind regards,
Tarjei

**Comment by tommikaikkonen** [comment]
Did not know about the possible performance penalty with try catch. I'll see if I can remove similar codeblocks in the library (I think there are a couple places I use that). Thanks!

About the paging. The problem is still a bit vague to me. I think there are multiple ways you could handle that depending on the requirements of your app. You could hold the pagination information outside the Redux-ORM database (arrays of id's associated with each page) and use those to look the real entities up from the Redux-ORM database, given that you've merged the paginated data from each server response. Or, you could add a field to each entity indicating the page they're on. etc...

If you can give a concrete example of input you're getting from the server and what you want to achieve on the front end (what props would you want to pass to React?), I can give a more thorough answer.

I have not used Immutable.js with Redux-ORM. If you wanted the database managed by Redux-ORM to be using Immutable.js, you would override the Backend class.

But, for everything except entity properties pointing to reference values (objects or arrays), Redux-ORM takes care of immutability internally. For most cases, you'd use Immutable.js for any state you manage outside Redux-ORM, and let it handle immutability for it's own relational database state.

**Comment by tarjei** [comment]
Hi Tommi, I'm sorry for a bit late reply.

Anyhow, the distinction I am trying to make here is bigger than just pagination. Think of it as a subset of the problem of serverside filtering of data.

Let's say I got a Book object in my schema: 

```
import {fk, many, Model} from 'redux-orm';

class Book extends Model {
    toString() {
        return `Book: ${this.name}`;
    }
    // Declare any static or instance methods you need.
}
Book.modelName = 'Book';

```

Now, I'm the library of congress and I got millions of books in my store. Now, I'm going to fetch the 100 most relevant books for this user and the user is going to edit the books. I.e. I call the server with a call like `GET /books?user=tommi` and I get a response suggesting a total of 1000 books but only returns 10 of them. 

It could be argued that interactions like this one should be handled within one component, but lets put that aside for a moment. What I want to achieve is a standard way of handling server side filters.

My point is that the ORM should contain a standard way to handle this use case so that each book is placed in the book store with a separate ordered list stored as a representation of the query done against the server.

T

**Comment by tommikaikkonen** [comment]
OK, this answer got long. I hope you get some ideas out of this :)

I'm hesitant to implement functionality for this use case in the core package. Many apps don't need to store data specific to queries. I think it's important for the library to provide an easy way to build an extension that handles cases like this though.

If you need detailed data on queries, you need to store data about the queries somewhere in the state. You could do that inside or outside Redux-ORM.

**Outside Redux-ORM**, you could have an ordered array of book id's for each query. Then, you would implement selectors like this:

```javascript
// Get the query object, which could be in the form { itemIds: [123, 432, 333, ...] }
const getSelectedBookQuery = state => state.queries.Book[state.selectedQueryId];

const bookQuerySelector = createSelector(
    state => state.orm,
    getSelectedBookQuery,
    schema.createSelector((session, selectedQuery) => {
        const qs = session.Book.getQuerySetWithIds(selectedQuery.itemIds);
        // possibly qs.paginate()...
        return qs.toRefArray();
        // Returns an array thats items are references to plain book objects in the store
    });
);
```

That's pretty simple. If you're only storing queries and the id's they got as a response, writing a reducer for `state.queries` is straightforward as you're only adding new queries, not editing or deleting previous ones.

**Inbetween**
You could basically store this kind of data inside Redux-ORM, but not controlled by the ORM API. You could manage an additional part of state, by adding `meta` key in addition to the normal `items` and `itemsById`

```javascript
// Model state
{
    items: [],
    itemsById: {},
    meta: {/* whatever you want, like selectedItemId: 5, queries: { } ...*/}
}
```

You would have access to this in your Model reducer (`state.meta`), and you can handle it's edits in the same model reducer after `getNextState`, or separate it to a metaReducer like this:

```javascript
// Implement a mixin that adds meta state and metaReducer to a model class.
// It's all just ES6 and classes.
const metaStateMixin = superclass => class extends superclass {
    // Default, overridable implementation.
    static metaReducer(metaState = {}, action, model, session) {
        return metaState;
    }

    static reducer(state, action, model, session) {
        let nextState = model.getNextState();

        const nextMeta = this.metaReducer(state, action, model, session);

        // Handle immutability and structural sharing.
        if (state === nextState) {
            if (state.meta !== nextMeta) {
                nextState = { ...nextState, meta: nextMeta };
            }
        } else {
            nextState.meta = nextMeta;
        }
        return nextState;
    }
}

const baseModelWithMetaData = metaStateMixin(Model);

class MyModelWithMetaData extends baseModelWithMetaData {
    static metaReducer(state = {}, action, model, session) {
        const { type, payload } = action;
        switch (type) {
        case 'RECEIVE_BOOKS':
            return {
                ...state,
                queries: {
                    ...state.queries,
                    [payload.queryId]: payload.itemIds,
                },
            };
        default:
            return state;
        }
    }

    static reducer(state, action, model, session) {
        // do your stuff...
        
        return super.reducer(state, action, model, session);
    }
}

// in a selector, you have access to meta through `Model.state.meta`...
schema.createSelector((session, queryId) => {
    const ids = MyModelWithMetaData.state.meta.queries[0].itemIds
    return MyModelWithMetaData.getQuerySetFromIds(ids).toRefArray();
});

```

That's not much different than storing the same data outside Redux-ORM, but gives you the convenience of having easy access to the metadata.

Now, if you wanted to do this **inside Redux-ORM with relations**.

Having a Query model with a many-to-many relation with Book would solve the unordered case using a relational database. You would use `queryInstance.books.doSomething()`. The through model would need an additional `position` integer field to resolve the order, assuming one book can belong to multiple queries. This is achievable with custom through models, but they aren't implemented yet.

When that's possible, you could do this.

```javascript

// The through model.
class QueryPosition extends Model {}
QueryPosition.fields = {
    query: fk('Query', 'queryPositions'),
    book: fk('Book', 'queryPositions'),
}
// Using redux-orm-proptypes notation to indicate the non-relational `position` field.
QueryPosition.propTypes = {
    query: PropTypes.number.isRequired,
    book: PropTypes.number.isRequired,
    // Record the book's position in the query.
    position: PropTypes.number.isRequired,
}

class Query extends Model {}
Query.fields = {
    books: many('Book', {
        throughModel: 'QueryPosition',
        fromFieldName: 'query',
        toFieldName: 'book',
        reverseFieldName: 'queries'
    }),
}

// How to receiving books from a query response

// Somewhere inside the Query reducer.
const query = Query.create({ id: payload.queryId, queryString: payload.queryString });


// Somewhere inside the QueryPosition reducer.
payload.receivedBooks.forEach((book, index) => {
    QueryPosition.create({
        query: payload.queryId,
        book: book.id,
        position: index
    })
})

// And thus, you could implement a selector like this.
const querySelector = createSelector(
    state => state.orm,
    state => state.selectedQueryId,
    schema.createSelector((session, queryId) => {
        return session.QueryPosition.filter({ query: queryId })
            .orderBy('position')
            .map(queryPosition => queryPosition.book.ref);
        // returns a list of books in the order that we got them in the query
    })
);
```

But how would you abstract this? A Model factory is one option. You can see how I implemented the [`redux-orm-proptypes` mixin](https://github.com/tommikaikkonen/redux-orm-proptypes/blob/master/src/index.js), which is implemented as a model factory, but also provides a meta factory, or a *model factory factory* :)

```javascript

// Factory for Query & QueryPosition models
const manageQueriesForModel = (modelToManage, queryBaseModel = Model, positionBaseModel = Model) => {
    // Resolve the modelNames we'll be using for the query-related models.
    const queryPositionModelName = modelToManage.modelName + 'QueryPosition';
    const queryModelName = modelToManage.modelName + 'Query';

    const toFieldName = modelToManage.modelName.toLowerCase();

    class QueryPosition extends positionBaseModel {}
    QueryPosition.modelName = queryPositionModelName;
    QueryPosition.fields = {
        query: fk(queryModelName, 'queryPositions'),
        [toFieldName]: fk(modelToManage.modelName, 'queryPositions')
    };

    class Query extends queryBaseModel {
        orderedItems() {
            const orderedItemIds = this.queryPositions
                .orderBy('position')
                .map(position => position[toFieldName]);

            // We can access the current session with this.session.
            return this.session[modelToManage.modelName]
                .getQuerySetWithIds(orderedItemIds);
        }
    }

    Query.fields = Object.assign({}, queryBaseModel.fields, {
        items: many(modelToManage.modelName, {
            throughModel: QueryPosition,
            fromFieldName: 'query',
            toFieldName: modelToManage.modelName.toLowerCase(),
            reverseFieldName: 'queries',
            throughFieldName: 'queryPositions'
        })
    });

    Query.modelName = queryModelName;

    return [Query, QueryPosition];
}

// manageQueriesForModel could be published as a separate package.
const [BookQuery, BookQueryPosition] = manageQueriesForModel(Book);
const [AuthorQuery, AuthorQueryPosition] = manageQueriesForModel(Author);

BookQuery.reducer = state => state; // can implement your reducer here
AuthorQuery.reducer = state => state; /// and here...

const schema = new Schema();
schema.register(Book, BookQuery, BookQueryPosition, AuthorQuery, AuthorQueryPosition);

// Now you could implement a selector like this.
const bookQuerySelector = createSelector(
    state => state.orm,
    state => state.selectedQueryId,
    schema.createSelector((session, queryId) => {
        return session.BookQuery.withId(queryId).orderedItems().toRefArray();
    })
);
```

Which one of these options is best depends on how complex data and relation-spanning logic you need associated with your queries.

**Comment by tarjei** [comment]
Great answer, thanks!

Now is the time where I get my hands very dirty trying out different approaches :+1:
