### ISSUE TITLE
Selectors in 0.9, how is session created?

### ISSUE THREAD

**Issue by Aryk** [tommikaikkonen/redux-orm#70]
I was looking at the code here:

```js
export function createSelector(orm, ...args) {
    if (args.length === 1) {
        return memoize(args[0], eqCheck, orm);
    }

    return createSelectorCreator(memoize, eqCheck, orm)(...args);
}
```
and then the code in the new 0.9 docs:

```js
const mySelector = createSelector(orm, state => state.orm, session => {
    return session.Book.all().toRefArray();
});
```

It seems like the state => state.orm would become the input to the resultFunc with session, but given the implementation, shouldn't it be:

```js
const mySelector = createSelector(orm, state => state.orm, ormState => {
   const session = orm.session(ormState);
   return session.Book.all().toRefArray();
});
```

Or is there some more code that I'm not seeing that initiates the session?

**Comment by tommikaikkonen** [comment]
It's done in the custom `memoize` function provided by Redux-ORM https://github.com/tommikaikkonen/redux-orm/blob/feature/eager_updates/src/memoize.js#L69. `reselect` accepts that as an argument to `createSelectorCreator`. It would probably be cleaner to handle the Session instantiation in `createSelector` as the process of memoization isn't really related to it - but on the other hand, the memoization relies on checking which Models were accessed in the user-supplied selector function to determine when it can return a memoized result.

Also beware of name clashes if you're using plain `reselect` on the side - `createSelector` is identically named to the `reselect.createSelector`.

**Comment by Aryk** [comment]
Ah, that was a PEBKAC! I missed the custom memoize function. Thanks for your help. It all makes sense now!
