### ISSUE TITLE
Suggestion: QuerySet.at should return undefined when not in this.rows

### ISSUE THREAD

**Issue by Aryk** [tommikaikkonen/redux-orm#73]
Currently, if you filter down and call `at` and doesn't exist, it will still return something that is truthy, making calls like:

const record = model.associations.first()
if (record) {

}

not work correctly. Was this intended?

**Comment by Aryk** [comment]
@tommikaikkonen , any thoughts on this? seems like it would be an easy fix to simply check if the record is there.

**Comment by tommikaikkonen** [comment]
Thanks for opening the issue and sorry for the delay. This was not intended functionality. With `0.9.0-rc.2`, it'll return `undefined` when the index to access is out of bounds, like normal JavaScript Arrays.

**Comment by Aryk** [comment]
No problem, thanks for adding it in!
