### ISSUE TITLE
Bug: Cannot change idAttribute's value 

### ISSUE THREAD

**Issue by iZaL** [tommikaikkonen/redux-orm#74]
While playing with the latest version (0.9.0-rc.1) of the library, I encountered a bug where the model's ID is being set to **id** regardless of the value set in backend object's idAttribute. 
ex :

`Property.backend = {
  idAttribute: '_id'
};`

So, Instead of setting the **idAttribute** to **_id**, the idAttribute property always returns **id**.

**Comment by tommikaikkonen** [comment]
Thanks for opening the issue! With some internal changes (Backend class was eliminated) in 0.9.0, I renamed `Model.backend` to `Model.options` which I think is a clearer name, but forgot to document that. Sorry about that.

I added a note about the renamed property to README.md in the master branch, will add a note about this to the migration guide. I added backwards compatibility to `backend` in  `0.9.0-rc.2` with a deprecation warning.
