### ISSUE TITLE
Don't use es6 classes

### ISSUE THREAD

**Issue by danny-andrews** [tommikaikkonen/redux-orm#8]
This is a contentious issue I realize, but using es6 classes in a library necessitates its use in any apps which consume that library. Many people are on the fence about es6 classes, and would prefer not to have them leak into their apps.

**Comment by tommikaikkonen** [comment]
Hey Danny, thanks for opening the issue.

I agree that we should avoid classes when it's feasible, but I'm not sure that's the right choice for Model classes. Other parts of the codebase could be done without classes, though, but they're mainly internals.

The difficulty is that for models, you'll often want to chain methods. You add some validation on top of `create` and `update`. Then you add some hooks on top of that. Etc. That's super easy to do with classes `super`. That's harder with composing.

I'd be happy to hear you out if you have an idea of how a class-less implementation would look like for the user!

**Comment by danny-andrews** [comment]
That makes sense, js doesn't make it easy to do that kind of classical inheritance without rolling your own  system.

Thanks for making this repo! Dealing with related data in my redux app was a huge blocker, but now it looks like I'm going to finish on time!
