### ISSUE TITLE
dist/redux-orm.js isn't being built correctly

### ISSUE THREAD

**Issue by foxnewsnetwork** [tommikaikkonen/redux-orm#80]
The Problem
===
Just installed redux-orm at version `0.9.0-rc.2` into my project, but for various reasons like being client-side browser, I must use `dist/redux-orm.js` instead of directly accessing the contents in `lib/index.js`. However, upon inspecting the files in my `node_modules`, I noticed following:

![screen shot 2017-01-10 at 3 06 38 pm](https://cloud.githubusercontent.com/assets/1010423/21828635/7084e8bc-d746-11e6-8258-f0d1f04f60e0.png)

Notably, that there is no line that states (I did try searching for it also):

```javascript
exports.attr = ... ;
```

However, in `lib/index.js`, it seems `exports.attr = _fields.attr;` is properly included. This suggests to me that `dist/redux-orm.js` might be several versions behind what the `package.json` says.

Suggestions
===
It seems to me something is wrong with the NPM guy's publishing system that they're ignoring your pre-publish results. Would it be unreasonable to humbly request you just commit your `dist` into your repo?

Miscellaneous
===
Also, for folks who are using `dist/redux-orm.js`, it seems custom idAttributes of the form `Book.options = { idAttribute: 'isbn' }` or whatever is currently broken because, whatever version `dist/redux-orm.js` is actually running, I suspect it still expects `backend` and not `options`

**Comment by tommikaikkonen** [comment]
Thanks for opening the issue! The published browser build was updated four days ago (I forgot to update it when I pushed 0.9.0-rc.2). You can see that it includes the [`attr` export](https://tommikaikkonen.github.io/redux-orm/dist/redux-orm.js).

Upon further inspection to the contents of `node_modules/redux-orm` after a fresh install, there's something odd happening there with the build process. `dist/redux-orm.js` is out of date, `lib/index.js` is up to date... I also need to add some directories to npmignore. Will look at this today and publish a fix given I resolve the issues.

**Comment by foxnewsnetwork** [comment]
Hooray, thank you, let me know if there's anything I can do to help

**Comment by tommikaikkonen** [comment]
I just released `0.9.0-rc.3`. I added the normal babel transpiling build (output in `lib/`) alongside the UMD build in `dist/redux-orm.js`. Since 0.8.4 the main entry point in `package.json` was pointing to `dist/redux-orm.js` but now it's pointing back to `lib/index.js`. Hopefully this fixes your issue!

**Comment by foxnewsnetwork** [comment]
It absolutely does, stuff in `dist/redux-orm.js` now magically work again. Thanks so much for taking time to resolve this. Will close
