### ISSUE TITLE
How can i select a result?

### ISSUE THREAD

**Issue by BrunoQuaresma** [tommikaikkonen/redux-orm#84]
1. I fetched 10 books. So, when I click in some book I want fetch more informations from this selected book. How can i do this? 

2. If the redux-orm saves in the store data from many items. The key name, by default, not to be in plural?

**Comment by markerikson** [comment]
For the first question, I've got some examples in my blog post at http://blog.isquaredsoftware.com/2016/12/practical-redux-part-5-loading-and-displaying-data/.

For the second, the table names are based on the names you give your model.  If I create a model with `class Pilot extends Model`, the "table" name will be `Pilot`.  I prefer to give them a singular name.

**Comment by BrunoQuaresma** [comment]
Thanks @markerikson
