### ISSUE TITLE
Reason for special case in schema.createSelector?

### ISSUE THREAD

**Issue by danny-andrews** [tommikaikkonen/redux-orm#9]
I wrote a selector with `schema.createSelector`, and I was trying to assert on selector.recomputations(), but I got `recomputations is not a function`. When I looked into it, it looks like it's because of this special case [here](https://github.com/tommikaikkonen/redux-orm/blob/master/src/Schema.js#L381). Is there a reason for this? It would be nice to be able to create a selector with `schema.createSelector` and get all the features of createSelectorCreator from reselect.

Thanks!

**Comment by tommikaikkonen** [comment]
`reselect` always requires one or more input selectors in addition to the selector you're defining. `redux-orm` makes it possible to define a selector without an input selector (in this case, the selector expects the ORM state object). There's two ways to do that: use `reselect` with an identity function as the sole input selector, or just memoize the function passed to `createSelector`. I chose the latter as it is slightly less overhead, but it doesn't implement the `recomputations` method.

If you want to check the recomputations, you can create the selector using the first approach, by passing an identity function before the selector function you defined.

```javascript
const identity = ormState => ormState;
schema.createSelector(identity, ormSession => ...);
```

**Comment by danny-andrews** [comment]
Got it, thanks for the clarification!

**Comment by thedeeno** [comment]
Can we close this?
