### ISSUE TITLE
Example of how to implement new 'through' models

### ISSUE THREAD

**Issue by greatwillow** [tommikaikkonen/redux-orm#92]
Currently, I'm trying to understand how to implement the new 'through' models paradigm as introduced recently (in version 0.9.0 I believe).  I have read up on this here: 

https://github.com/tommikaikkonen/redux-orm/blob/feature/eager_updates/src/fields.js#L330

...and have implemented this in my code, though don't quite understand how to utilize this.  I was wondering if there was a more thorough example I could check out that would provide some insight into how this is used.  Thanks!

**Comment by vamsiampolu** [comment]
If I specify a many to many relationship between 2 models, it automatically creates a through model. When would I need to use a through model manually?

**Comment by plandem** [comment]
You will need it when you want to store additional info. E.g. at your DB you have special table for links and some additional extra fields at the same table. So you would like to have this information.
