### ISSUE TITLE
Redux-ORM test adapter in factory-girl

### ISSUE THREAD

**Issue by carlesnunez** [tommikaikkonen/redux-orm#93]
Hello @tommikaikkonen 

I've been learning with your redux-orm-primer example about how to test redux-rom models. But when I arrived to reduxORMAdapter I've seen that this was a bit deprecated. Factory girl now is no version 4 and in redux-orm-primer example we are using an old version. Then I've decided to create my own adapter and I have started a PR on factory-girl project:

https://github.com/aexmachina/factory-girl/pull/87

It will be nice if you look at the PR and make an OK if you like what you see.

I'll will try in the next days to make an update on Redux-ORM-primer example to update the code to the new version of redux-orm and factory-girl

Thank you, Carles

**Comment by carlesnunez** [comment]
That was merged and added to the last version of factory-girl

**Comment by haveyaseen** [comment]
See #97.
