### ISSUE TITLE
Retrieve ids of related model from selector`

### ISSUE THREAD

**Issue by vamsiampolu** [tommikaikkonen/redux-orm#95]
I would like to create and reuse selectors within other selectors when using `createSelector` from 'redux-orm'. Assume I have a model called `Profile` and a model called `repos`.  To get a list of all repoIds when selecting a repo( the first repo to keep it simple):

```js
const profileTransform  = (session) => {
   const profileModel = session.Profile.first();
   const profile = profileModel.ref;
   const repos = profileModel.repos.toModelArray({repoId} => repoId)
   return {
      ...profile,
     repos
   }
} 
```

I have more related models whose ids I would like to retrieve from the selector and I do not want to do something like:

```js
const repos = profileModel.repos.toModelArray({repoId} => repoId)
```

Is there a way of retrieving the ids for all relations to the model instance either using `.ref` or any other method?

**Comment by haveyaseen** [comment]
This is now technically possible using indexes, but they're an internal API and not meant for direct access. The way you described is the proper one.

**Comment by haveyaseen** [comment]
Selectors are now composable with ID arguments! Please try out [v0.14.0-rc.0](https://github.com/redux-orm/redux-orm/releases/tag/v0.14.0-rc.0) :slightly_smiling_face:
