### ISSUE TITLE
Redux-orm factory girl adapter - factory-girl-redux-orm - 

### ISSUE THREAD

**Issue by carlesnunez** [tommikaikkonen/redux-orm#96]
Hello all, I created a node package called factory-girl-redux-orm. It is just an adapter for factory-girl. In next version of factory-girl it will be merged on the main project but meanwhile you can use.

https://github.com/carlesnunez/factory-girl-redux-orm
https://npmjs.com/package/factory-girl-redux-orm

Thanks

**Comment by haveyaseen** [comment]
See #97.
