### ISSUE TITLE
New example of redux-orm with react-native and tests

### ISSUE THREAD

**Issue by carlesnunez** [tommikaikkonen/redux-orm#97]
I have been working on a test project on react-native redux redux-orm and redux-thunk. In the attempt to explain with my words how to integrate react-native and redux with an external api using different tools.
Do you have also tests with snapshots, jasmine and factory-girl in their latests versions that I hope that will be interesting for you.
I explain the process of creation and I answer myself the questions and doubts that were emerging in the process of creation.

https://github.com/carlesnunez/react-native-weather-app

Sorry if my english skills in advance! Hope that it helps the comunity!
Star it if is helpfull! It will make me feel better to start future projects!

**Comment by chanan** [comment]
Thanks @carlesnunez your app has been very helpful example!

**Comment by carlesnunez** [comment]
Thanks to you for give me that feedback! 😊

**Comment by haveyaseen** [comment]
Hey, I added your repositories to the [Redux-ORM wiki](https://github.com/tommikaikkonen/redux-orm/wiki/Related-projects).
